;
; File generated by cc65 v 2.18 - Git 555282497
;
	.fopt		compiler,"cc65 v 2.18 - Git 555282497"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.forceimport	initmainargs
	.import		_vdp_rectangle
	.import		_vdp_blank
	.import		_getch
	.import		_graphics_initgraph
	.import		_graphics_textxy
	.import		_graphics_setcolor
	.import		_graphics_bar
	.export		_main

.segment	"RODATA"

L0016:
	.byte	$48,$61,$6C,$6C,$6F,$20,$53,$74,$65,$63,$6B,$73,$63,$68,$77,$65
	.byte	$69,$6E,$21,$00

; ---------------------------------------------------------------
; int __near__ __cdecl__ main (int, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp4
	lda     #$07
	jsr     _graphics_initgraph
	lda     #$6D
	jsr     _vdp_blank
	ldx     #$00
	txa
L0041:	ldy     #$02
	jsr     staxysp
	cmp     #$10
	txa
	sbc     #$00
	bvc     L000D
	eor     #$80
L000D:	bpl     L0007
	ldy     #$02
	lda     (sp),y
	jsr     _graphics_setcolor
	lda     #$10
	jsr     pusha0
	ldy     #$04
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	jsr     pusha
	lda     #<(L0016)
	ldx     #>(L0016)
	jsr     _graphics_textxy
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0041
	inx
	bra     L0041
L0007:	jsr     _getch
	ldx     #$00
	txa
L0042:	ldy     #$02
	jsr     staxysp
	cmp     #$10
	txa
	sbc     #$00
	bvc     L0020
	eor     #$80
L0020:	bpl     L001A
	ldy     #$02
	lda     (sp),y
	jsr     _graphics_setcolor
	lda     #$0A
	jsr     pusha0
	ldy     #$05
	jsr     ldaxysp
	jsr     mulax10
	ldy     #$0A
	jsr     incaxy
	jsr     pusha
	lda     #$64
	jsr     pusha0
	ldy     #$08
	jsr     ldaxysp
	jsr     mulax10
	ldy     #$14
	jsr     incaxy
	jsr     _graphics_bar
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0042
	inx
	bra     L0042
L001A:	jsr     _getch
	ldx     #$00
	txa
L0043:	ldy     #$02
	jsr     staxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L0032
	eor     #$80
L0032:	bpl     L002C
	ldy     #$02
	lda     (sp),y
	jsr     _graphics_setcolor
	ldy     #$05
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	ldy     #$10
	jsr     incaxy
	jsr     pusha
	ldy     #$06
	jsr     ldaxysp
	ldy     #$20
	jsr     incaxy
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	ldy     #$20
	jsr     incaxy
	jsr     _vdp_rectangle
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0043
	inx
	bra     L0043
L002C:	jsr     _getch
	ldx     #$00
	txa
	jmp     incsp8

.endproc

