;
; File generated by cc65 v 2.18 - Git 555282497
;
	.fopt		compiler,"cc65 v 2.18 - Git 555282497"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.forceimport	initmainargs
	.import		_vdp_rectangle
	.import		_vdp_blank
	.import		_getch
	.import		_graphics_initgraph
	.import		_graphics_textxy
	.import		_graphics_setcolor
	.import		_graphics_bar
	.export		_main

.segment	"RODATA"

L0025:
	.byte	$48,$61,$6C,$6C,$6F,$20,$53,$74,$65,$63,$6B,$73,$63,$68,$77,$65
	.byte	$69,$6E,$21,$00

; ---------------------------------------------------------------
; int __near__ __cdecl__ main (int, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp4
	lda     #$07
	jsr     _graphics_initgraph
	lda     #$00
	jsr     _vdp_blank
	lda     #$0F
	jsr     _graphics_setcolor
	lda     #$01
	jsr     pusha0
	ina
	jsr     pusha
	dea
	jsr     pusha0
	lda     #$64
	jsr     _vdp_rectangle
	lda     #$0E
	jsr     _graphics_setcolor
	lda     #$01
	jsr     pusha0
	ina
	jsr     pusha
	lda     #$64
	jsr     pusha0
	lda     #$02
	jsr     _vdp_rectangle
	jsr     _getch
	ldx     #$00
	txa
L0050:	ldy     #$02
	jsr     staxysp
	cmp     #$10
	txa
	sbc     #$00
	bvc     L001C
	eor     #$80
L001C:	bpl     L0016
	ldy     #$02
	lda     (sp),y
	jsr     _graphics_setcolor
	lda     #$10
	jsr     pusha0
	ldy     #$04
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	jsr     pusha
	lda     #<(L0025)
	ldx     #>(L0025)
	jsr     _graphics_textxy
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0050
	inx
	bra     L0050
L0016:	jsr     _getch
	ldx     #$00
	txa
L0051:	ldy     #$02
	jsr     staxysp
	cmp     #$10
	txa
	sbc     #$00
	bvc     L002F
	eor     #$80
L002F:	bpl     L0029
	ldy     #$02
	lda     (sp),y
	jsr     _graphics_setcolor
	lda     #$0A
	jsr     pusha0
	ldy     #$05
	jsr     ldaxysp
	jsr     mulax10
	ldy     #$0A
	jsr     incaxy
	jsr     pusha
	lda     #$64
	jsr     pusha0
	ldy     #$08
	jsr     ldaxysp
	jsr     mulax10
	ldy     #$14
	jsr     incaxy
	jsr     _graphics_bar
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0051
	inx
	bra     L0051
L0029:	jsr     _getch
	ldx     #$00
	txa
L0052:	ldy     #$02
	jsr     staxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L0041
	eor     #$80
L0041:	bpl     L003B
	ldy     #$02
	lda     (sp),y
	jsr     _graphics_setcolor
	ldy     #$05
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	ldy     #$10
	jsr     incaxy
	jsr     pusha
	ldy     #$06
	jsr     ldaxysp
	ldy     #$20
	jsr     incaxy
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	ldy     #$20
	jsr     incaxy
	jsr     _vdp_rectangle
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0052
	inx
	bra     L0052
L003B:	jsr     _getch
	ldx     #$00
	txa
	jmp     incsp8

.endproc

