;
; File generated by cc65 v 2.18 - Git 55528249
;
	.fopt		compiler,"cc65 v 2.18 - Git 55528249"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.forceimport	initmainargs
	.import		_kbhit
	.import		_vdp_screen
	.import		_vdp_plot
	.export		_main

; ---------------------------------------------------------------
; int __near__ __cdecl__ main (int, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp4
	lda     #$07
	jsr     _vdp_screen
	ldx     #$00
	txa
L0024:	ldy     #$02
	jsr     staxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L000B
	eor     #$80
L000B:	bpl     L001C
	ldx     #$00
	txa
L0023:	jsr     stax0sp
	cmp     #$D4
	txa
	sbc     #$00
	bvc     L0015
	eor     #$80
L0015:	bpl     L0006
	ldy     #$05
	jsr     pushwysp
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _vdp_plot
	jsr     ldax0sp
	ina
	bne     L0023
	inx
	bra     L0023
L0006:	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0024
	inx
	bra     L0024
L001C:	jsr     _kbhit
	tax
	beq     L001C
	ldx     #$00
	txa
	jmp     incsp8

.endproc

