.PHONY: all clean
all: build

clean:
	(cd pacman; make clean)
	(cd dinosaur; make clean)
	(cd pong; make clean)
	(cd asteroids; make clean)
	(cd microchess; make clean)


build:
	(cd pacman; make )
	(cd dinosaur; make )
	(cd pong; make )
#	(cd asteroids; make )
	(cd microchess; make )

test:
	
