MAKEFILE=Makefile
all: build
clean:
	(cd clavier; make clean)
	(cd midi; make clean)
	(cd edlib; make clean)
	(cd ehbasic_65c02; make clean)
	(cd imfplayer; make clean)
	(cd joystick; make clean)
	(cd ppmview; make clean)
	(cd unrclock; make clean)

build:
	(cd clavier; make)
#	(cd midi; make)
	(cd edlib; make)
	(cd ehbasic_65c02; make)
	(cd imfplayer; make)
	(cd joystick; make)
	(cd ppmview; make)
	(cd unrclock; make)

