;       0       2       4       6       8       a       c       e      10      12      14      16      18      1a              1e  1f
.byte $00,$d0,$d2,$d2,$d2,$d2,$d2,$d2,$d2,$d2,$d4,$00,$00,$00,$da,$20,$db,$00,$00,$00,$d0,$d2,$d2,$d2,$d2,$d6,$d8,$d2,$d2,$d2,$d2,$d4 ; 0
.byte '0',$da,$cc,$cc,$ce,$cc,$cc,$cc,$cc,$cc,$db,$00,$00,$00,$da,$20,$db,$00,$00,$00,$da,$cc,$cc,$cc,$ce,$dc,$e1,$cc,$cc,$cc,$cc,$db
.byte '0',$da,$cc,$e2,$e6,$e4,$cc,$e2,$e4,$cc,$db,$00,$00,$00,$da,$20,$db,$00,$00,$00,$da,$cc,$e2,$e4,$cc,$e3,$e5,$cc,$e2,$e4,$cc,$db
.byte $00,$da,$cc,$dc,$00,$e1,$cc,$dc,$e1,$cc,$db,$00,$00,$00,$da,$20,$db,$00,$00,$00,$da,$cc,$dc,$e1,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$db
.byte $00,$da,$cc,$dc,$00,$e1,$cc,$dc,$e1,$cc,$db,$00,$00,$00,$da,$20,$db,$00,$00,$00,$da,$cc,$dc,$ee,$e6,$e6,$e4,$cc,$dc,$e1,$cc,$db ; 4
.byte $00,$da,$cc,$e3,$e7,$e5,$cc,$e3,$e5,$cc,$e3,$d2,$d2,$d2,$e5,$20,$e3,$d2,$d2,$d2,$e5,$cc,$e3,$e7,$e7,$e7,$e5,$cc,$dc,$e1,$cc,$db
.byte $00,$da,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$db
.byte $00,$da,$cc,$e2,$e6,$e4,$cc,$e2,$e6,$e6,$e6,$e6,$e6,$e6,$e4,$20,$e2,$e6,$e6,$e6,$e4,$cc,$e2,$e4,$cc,$e2,$e6,$e6,$f0,$e1,$cc,$db
.byte $00,$da,$cc,$dc,$00,$e1,$cc,$e3,$e7,$e7,$f1,$ef,$e7,$e7,$e5,$20,$e3,$e7,$e7,$e7,$e5,$cc,$dc,$e1,$cc,$e3,$e7,$e7,$f1,$e1,$cc,$db ; 8
.byte 'H',$da,$cc,$dc,$00,$e1,$cc,$cc,$cc,$cc,$dc,$e1,$20,$20,$20,$20,$20,$20,$20,$20,$20,$cc,$dc,$e1,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$db
.byte 'G',$da,$cc,$dc,$00,$e1,$cc,$e2,$e4,$cc,$dc,$e1,$20,$e8,$d3,$d3,$d3,$ea,$20,$e2,$e4,$cc,$dc,$e1,$cc,$e2,$e4,$cc,$dc,$e1,$cc,$db ; a
.byte 'I',$da,$cc,$e3,$e7,$e5,$cc,$dc,$e1,$cc,$e3,$e5,$20,$db,$20,$20,$20,$da,$20,$dc,$e1,$cc,$e3,$e5,$cc,$dc,$e1,$cc,$e3,$e5,$cc,$db
.byte 'H',$da,$cc,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$20,$20,$20,$ec,$20,$20,$20,$da,$20,$dc,$e1,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$cc,$cc,$cc,$db ; c
.byte $00,$f2,$e6,$e6,$e6,$e4,$cc,$dc,$ee,$e6,$e6,$e4,$20,$cf,$20,$20,$20,$da,$20,$dc,$ee,$e6,$e6,$e4,$20,$dc,$ee,$e6,$e6,$e4,$cc,$db ; d
.byte '0',$f3,$e7,$e7,$e7,$e5,$cc,$dc,$ef,$e7,$e7,$e5,$20,$cf,$20,$20,$20,$da,$20,$dc,$ef,$e7,$e7,$e5,$20,$dc,$ef,$e7,$e7,$e5,$cc,$db
.byte '0',$da,$cc,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$20,$20,$20,$ed,$20,$20,$20,$da,$20,$dc,$e1,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$cc,$cc,$cc,$db
.byte $00,$da,$cc,$e2,$e6,$e4,$cc,$dc,$e1,$cc,$e2,$e4,$20,$db,$20,$20,$20,$da,$20,$dc,$e1,$cc,$e2,$e4,$cc,$dc,$e1,$cc,$e2,$e4,$cc,$db ; 10
.byte $00,$da,$cc,$dc,$00,$e1,$cc,$e3,$e5,$cc,$dc,$e1,$20,$e9,$d2,$d2,$d2,$eb,$20,$e3,$e5,$cc,$dc,$e1,$cc,$e3,$e5,$cc,$dc,$e1,$cc,$db
.byte $00,$da,$cc,$dc,$00,$e1,$cc,$cc,$cc,$cc,$dc,$e1,$20,$20,$20,$20,$20,$20,$20,$20,$20,$cc,$dc,$e1,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$db ; 12
.byte $00,$da,$cc,$dc,$00,$e1,$cc,$e2,$e6,$e6,$f0,$ee,$e6,$e6,$e4,$20,$e2,$e6,$e6,$e6,$e4,$cc,$dc,$e1,$cc,$e2,$e6,$e6,$f0,$e1,$cc,$db
.byte $00,$da,$cc,$e3,$e7,$e5,$cc,$e3,$e7,$e7,$e7,$e7,$e7,$e7,$e5,$20,$e3,$e7,$e7,$e7,$e5,$cc,$e3,$e5,$cc,$e3,$e7,$e7,$f1,$e1,$cc,$db ; 14
.byte $00,$da,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$db
.byte 'P',$da,$cc,$e2,$e6,$e4,$cc,$e2,$e4,$cc,$e2,$d3,$d3,$d3,$e4,$20,$e2,$d3,$d3,$d3,$e4,$cc,$e2,$e6,$e6,$e6,$e4,$cc,$dc,$e1,$cc,$db
.byte 'U',$da,$cc,$dc,$00,$e1,$cc,$dc,$e1,$cc,$db,$00,$00,$00,$da,$20,$db,$00,$00,$00,$da,$cc,$dc,$ef,$e7,$e7,$e5,$cc,$dc,$e1,$cc,$db
.byte '1',$da,$cc,$dc,$00,$e1,$cc,$dc,$e1,$cc,$db,$00,$00,$00,$da,$20,$db,$00,$00,$00,$da,$cc,$dc,$e1,$cc,$cc,$cc,$cc,$dc,$e1,$cc,$db ; 18
.byte $00,$da,$cc,$e3,$e7,$e5,$cc,$e3,$e5,$cc,$db,$00,$00,$00,$da,$20,$db,$00,$00,$00,$da,$cc,$e3,$e5,$cc,$e2,$e4,$cc,$e3,$e5,$cc,$db
.byte $00,$da,$cc,$cc,$ce,$cc,$cc,$cc,$cc,$cc,$db,$00,$00,$00,$da,$20,$db,$00,$00,$00,$da,$cc,$cc,$cc,$ce,$dc,$e1,$cc,$cc,$cc,$cc,$db ; 1a
.byte $00,$d1,$d3,$d3,$d3,$d3,$d3,$d3,$d3,$d3,$d5,$00,$00,$00,$da,$20,$db,$00,$00,$00,$d1,$d3,$d3,$d3,$d3,$d7,$d9,$d3,$d3,$d3,$d3,$d5

; CREDIT  0   HIGH      00

; 1UP      00 HIGH      00
;##########################
;#           ##           #
;# ### ##### ## ##### ### #
;# # # #   # ## #   # # # #
;# ### ##### ## ##### ### #
;#                        #
;# ### ## ######## ## ### #
;# ### ## ######## ## ### #
;#     ##    ##    ##     #
;##### ##### ## ##### #####
;    # ##### ## ##### #
;    # ##  RRRRRR  ## #
;    # ## ######## ## #
;##### ## #      # ## #####
;TTTTT    #      #    TTTTT
;##### ## #      # ## #####
;    # ## ######## ## #
;    # ##          ## #
;    # ## ######## ## #
;##### ## ######## ## #####
;#           ##           #
;# ### ##### ## ##### ### #
;# ### ##### ## ##### ### #
;#  ##     RRRRRR     ##  #
;## ## ## ######## ## ## ##    ^
;## ## ## ######## ## ## ##  --|
;#     ##    ##    ##     #
;# ######### ## ######### #
;# ######### ## ######### #
;#                        #
;##########################

;R => red zone, consider char $cc vs. $8c and $20 vs. $60, or use position
;T => tunnel, consider $20 vs. $a0 (bit 7)
