fortune0:
.byte "I don't care where I sit as long as I ",$0a
.byte "get fed.",$0a
.byte "-- Calvin Trillin",$0a
.byte $0a, 0
fortune1:
.byte "Trespassers will be shot.  Survivors ",$0a
.byte "will be prosecuted.",$0a
.byte $0a, 0
fortune2:
.byte "Children begin by loving their ",$0a
.byte "parents.  After a time they judge them.",$0a
.byte "Rarely, if ever, do they forgive them.",$0a
.byte "-- Oscar Wilde",$0a
.byte $0a, 0
fortune3:
.byte "prairies, n.:",$0a
.byte "Vast plains covered by ",$0a
.byte "treeless forests.",$0a
.byte $0a, 0
fortune4:
.byte "Don't wake me up too soon...",$0a
.byte "Gonna take a ride across the moon...",$0a
.byte "You and me.",$0a
.byte $0a, 0
fortune5:
.byte "Half a mind is a terrible thing to ",$0a
.byte "waste!",$0a
.byte $0a, 0
fortune6:
.byte "<dark> Yes, your honour, I have RSA ",$0a
.byte "encryption code tattood on my",$0a
.byte "        penis.  Shall I show the jury?",$0a
.byte $0a, 0
fortune7:
.byte "C Code.",$0a
.byte "C Code Run.",$0a
.byte "Run, Code, RUN!",$0a
.byte "PLEASE!!!!",$0a
.byte $0a, 0
fortune8:
.byte "BOFH excuse #409:",$0a
.byte "",$0a
.byte "The vulcan-death-grip ping has been ",$0a
.byte "applied.",$0a
.byte $0a, 0
fortune9:
.byte "If God had not given us sticky tape, ",$0a
.byte "it would have been necessary to invent ",$0a
.byte "it.",$0a
.byte $0a, 0
fortune10:
.byte "Old Mother Hubbard went to the cupboard",$0a
.byte "To fetch her poor daughter a dress.",$0a
.byte "When she got there, the cupboard was ",$0a
.byte "bare",$0a
.byte "And so was her daughter, I guess...",$0a
.byte $0a, 0
fortune11:
.byte "According to my best recollection, I ",$0a
.byte "don't remember.",$0a
.byte "-- Vincent Jimmy Blue ",$0a
.byte "Eyes Alo",$0a
.byte $0a, 0
fortune12:
.byte "In the future, you're going to get ",$0a
.byte "computers as prizes in breakfast ",$0a
.byte "cereals.",$0a
.byte "You'll throw them out because your ",$0a
.byte "house will be littered with them.",$0a
.byte $0a, 0
fortune13:
.byte "We'll pivot at warp 2 and bring all ",$0a
.byte "tubes to bear, Mr. Sulu!",$0a
.byte $0a, 0
fortune14:
.byte "Order and simplification are the first ",$0a
.byte "steps toward mastery of a subject",$0a
.byte "-- the actual enemy is the unknown.",$0a
.byte "-- Thomas Mann",$0a
.byte $0a, 0
fortune15:
.byte "History books which contain no lies ",$0a
.byte "are extremely dull.",$0a
.byte $0a, 0
fortune16:
.byte "The mind is its own place, and in ",$0a
.byte "itself",$0a
.byte "Can make a Heav'n of Hell, a Hell of ",$0a
.byte "Heav'n.",$0a
.byte "-- John Milton",$0a
.byte $0a, 0
fortune17:
.byte "How much of their influence on you is ",$0a
.byte "a result of your influence on them?",$0a
.byte $0a, 0
fortune18:
.byte "Words must be weighed, not counted.",$0a
.byte $0a, 0
fortune19:
.byte "The grand leap of the whale up the ",$0a
.byte "Fall of Niagara is esteemed, by all",$0a
.byte "who have seen it, as one of the finest ",$0a
.byte "spectacles in nature.",$0a
.byte "-- Benjamin Franklin.",$0a
.byte $0a, 0
fortune20:
.byte "Mate, this parrot wouldn't VOOM if you ",$0a
.byte "put four million volts through it!",$0a
.byte "-- Monty Python",$0a
.byte $0a, 0
fortune21:
.byte "You may get an opportunity for ",$0a
.byte "advancement today.  Watch it!",$0a
.byte $0a, 0
fortune22:
.byte "A gourmet who thinks of calories is ",$0a
.byte "like a tart that looks at her watch.",$0a
.byte "-- James Beard",$0a
.byte $0a, 0
fortune23:
.byte "<MFGolfBal> rit/ara:  There's ",$0a
.byte "something really demented about UNIX",$0a
.byte "            underwear...",$0a
.byte $0a, 0
fortune24:
.byte "The most exciting phrase to hear in ",$0a
.byte "science, the one that heralds new",$0a
.byte "discoveries, is not Eureka! (I found ",$0a
.byte "it!) but That's funny ...",$0a
.byte "-- Isaac Asimov",$0a
.byte $0a, 0
fortune25:
.byte "BOFH excuse #260:",$0a
.byte "",$0a
.byte "We're upgrading /dev/null",$0a
.byte $0a, 0
fortune26:
.byte "Ring around the collar.",$0a
.byte $0a, 0
fortune27:
.byte "Only a brain-damaged operating system ",$0a
.byte "would support task switching and not",$0a
.byte "make the simple next step of ",$0a
.byte "supporting multitasking.",$0a
.byte "-- George McFry",$0a
.byte $0a, 0
fortune28:
.byte "The first version always gets thrown ",$0a
.byte "away.",$0a
.byte $0a, 0
fortune29:
.byte "Some men feel that the only thing they ",$0a
.byte "owe the woman who marries them",$0a
.byte "is a grudge.",$0a
.byte "-- Helen Rowland",$0a
.byte $0a, 0
fortune30:
.byte "Life is a sexually transmitted disease ",$0a
.byte "with 100% mortality.",$0a
.byte $0a, 0
fortune31:
.byte "The mosquito is the state bird of New ",$0a
.byte "Jersey.",$0a
.byte "-- Andy Warhol",$0a
.byte $0a, 0
fortune32:
.byte "Did an Italian CRANE OPERATOR just ",$0a
.byte "experience uninhibited sensations in",$0a
.byte "a MALIBU HOT TUB?",$0a
.byte $0a, 0
fortune33:
.byte "If you marry a man who cheats on his ",$0a
.byte "wife, you'll be married to a man who",$0a
.byte "cheats on his wife.",$0a
.byte "-- Ann Landers",$0a
.byte $0a, 0
fortune34:
.byte "No matter how much you do you never do ",$0a
.byte "enough.",$0a
.byte $0a, 0
fortune35:
.byte "* joeyh cvs commits his home ",$0a
.byte "directory. Aaaaaa",$0a
.byte "<drow> eeeeeeek",$0a
.byte "<drow> joeyh: That is simply evil.  ",$0a
.byte "Period.",$0a
.byte $0a, 0
fortune36:
.byte "Beware of computerized fortune-tellers!",$0a
.byte $0a, 0
fortune37:
.byte "How's it going in those MODULAR LOVE ",$0a
.byte "UNITS??",$0a
.byte $0a, 0
fortune38:
.byte "An idealist is one who helps the other ",$0a
.byte "fellow to make a profit.",$0a
.byte "-- Henry Ford",$0a
.byte $0a, 0
fortune39:
.byte "I dunno, I dream in Perl sometimes...",$0a
.byte "-- Larry Wall in  ",$0a
.byte "<8538@jpl-devvax.JPL.NASA.GOV>",$0a
.byte $0a, 0
fortune40:
.byte "It is the business of little minds to ",$0a
.byte "shrink.",$0a
.byte "-- Carl Sandburg",$0a
.byte $0a, 0
fortune41:
.byte "BOFH excuse #299:",$0a
.byte "",$0a
.byte "The data on your hard drive is out of ",$0a
.byte "balance.",$0a
.byte $0a, 0
fortune42:
.byte "Be prepared to accept sacrifices.  ",$0a
.byte "Vestal virgins aren't all that bad.",$0a
.byte $0a, 0
fortune43:
.byte "The price of seeking to force our ",$0a
.byte "beliefs on others is that someday",$0a
.byte "they might force their beliefs on us.",$0a
.byte "-- Mario Cuomo",$0a
.byte $0a, 0
fortune44:
.byte "A free society is one where it is safe ",$0a
.byte "to be unpopular.",$0a
.byte "-- Adlai Stevenson",$0a
.byte $0a, 0
fortune45:
.byte "I won't mention any names, because I ",$0a
.byte "don't want to get sun4's into",$0a
.byte "trouble...  :-)     -- Larry Wall in ",$0a
.byte "<11333@jpl-devvax.JPL.NASA.GOV>",$0a
.byte $0a, 0
fortune46:
.byte "Life is the living you do, Death is ",$0a
.byte "the living you don't do.",$0a
.byte "-- Joseph Pintauro",$0a
.byte $0a, 0
fortune47:
.byte "When choosing between two evils, I ",$0a
.byte "always like to take the one I've never",$0a
.byte "tried before.",$0a
.byte "-- Mae West, Klondike ",$0a
.byte "Annie",$0a
.byte $0a, 0
fortune48:
.byte "Absolutely nothing should be concluded ",$0a
.byte "from these figures except that",$0a
.byte "no conclusion can be drawn from them.",$0a
.byte "-- Joseph L. Brothers, ",$0a
.byte "Linux/PowerPC Project)",$0a
.byte $0a, 0
fortune49:
.byte "I am very fond of the company of ",$0a
.byte "ladies.  I like their beauty,",$0a
.byte "I like their delicacy, I like their ",$0a
.byte "vivacity, and I like their silence.",$0a
.byte "-- Samuel Johnson",$0a
.byte $0a, 0
fortune50:
.byte "I didn't order any WOO-WOO ... Maybe a ",$0a
.byte "YUBBA ... But no WOO-WOO!",$0a
.byte $0a, 0
fortune51:
.byte "BOFH excuse #404:",$0a
.byte "",$0a
.byte "Sysadmin accidentally destroyed pager ",$0a
.byte "with a large hammer.",$0a
.byte $0a, 0
fortune52:
.byte "Planet Claire has pink hair.",$0a
.byte "All the trees are red.",$0a
.byte "No one ever dies there.",$0a
.byte "No one has a head....",$0a
.byte $0a, 0
fortune53:
.byte "15% gratuity added for parties over 8.",$0a
.byte $0a, 0
fortune54:
.byte "Of course a platonic relationship is ",$0a
.byte "possible -- but only between",$0a
.byte "husband and wife.",$0a
.byte $0a, 0
fortune55:
.byte "YOW!!  What should the entire human ",$0a
.byte "race DO??  Consume a fifth of",$0a
.byte "CHIVAS REGAL, ski NUDE down MT. ",$0a
.byte "EVEREST, and have a wild SEX WEEKEND!",$0a
.byte $0a, 0
fortune56:
.byte "You will wish you hadn't.",$0a
.byte $0a, 0
fortune57:
.byte "statistics, n.:",$0a
.byte "A system for expressing your ",$0a
.byte "political prejudices in convincing",$0a
.byte "scientific guise.",$0a
.byte $0a, 0
fortune58:
.byte "Used staples are good with SOY SAUCE!",$0a
.byte $0a, 0
fortune59:
.byte "Anything that is worth doing has been ",$0a
.byte "done frequently.  Things hitherto",$0a
.byte "undone should be given, I suspect, a ",$0a
.byte "wide berth.",$0a
.byte "-- Max Beerbohm, ",$0a
.byte "Mainly on the Air",$0a
.byte $0a, 0
fortune60:
.byte "Jesus saves...but Gretzky gets the ",$0a
.byte "rebound!",$0a
.byte "-- Daniel Hinojosa ",$0a
.byte "(hinojosa@hp-sdd)",$0a
.byte $0a, 0
fortune61:
.byte "HOORAY, Ronald!!  Now YOU can marry ",$0a
.byte "LINDA RONSTADT too!!",$0a
.byte $0a, 0
fortune62:
.byte "By golly, I'm beginning to think Linux ",$0a
.byte "really *is* the best thing since",$0a
.byte "sliced bread.",$0a
.byte "-- Vance Petree, ",$0a
.byte "Virginia Power",$0a
.byte $0a, 0
fortune63:
.byte "A man who turns green has eschewed ",$0a
.byte "protein.",$0a
.byte $0a, 0
fortune64:
.byte "Did you know the University of Iowa ",$0a
.byte "closed down after someone stole the ",$0a
.byte "book?",$0a
.byte $0a, 0
fortune65:
.byte "BOFH excuse #380:",$0a
.byte "",$0a
.byte "Operators killed when huge stack of ",$0a
.byte "backup tapes fell over.",$0a
.byte $0a, 0
fortune66:
.byte "To err is human -- but it feels divine.",$0a
.byte "-- Mae West",$0a
.byte $0a, 0
fortune67:
.byte "To kick or not to kick...",$0a
.byte "-- Somewhere on IRC, ",$0a
.byte "inspired by Shakespeare",$0a
.byte $0a, 0
fortune68:
.byte "A wide-eyed, innocent UNICORN, poised ",$0a
.byte "delicately in a MEADOW filled",$0a
.byte "with LILACS, LOLLIPOPS & small ",$0a
.byte "CHILDREN at the HUSH of twilight??",$0a
.byte $0a, 0
fortune69:
.byte "Absence in love is like water upon ",$0a
.byte "fire; a little quickens, but much",$0a
.byte "extinguishes it.",$0a
.byte "-- Hannah More",$0a
.byte $0a, 0
fortune70:
.byte "The opposite of talking isn't ",$0a
.byte "listening.  The opposite of talking is ",$0a
.byte "waiting.",$0a
.byte "-- Fran Lebowitz, ",$0a
.byte "Social Studies",$0a
.byte $0a, 0
fortune71:
.byte "A fanatic is a person who can't change ",$0a
.byte "his mind and won't change the subject.",$0a
.byte "-- Winston Churchill",$0a
.byte $0a, 0
fortune72:
.byte "Plastic gun.  Ingenious.  More ",$0a
.byte "coffee, please.",$0a
.byte "-- The Phantom comics",$0a
.byte $0a, 0
fortune73:
.byte "I am not sure what this is, but an ",$0a
.byte "`F' would only dignify it.",$0a
.byte "-- English Professor",$0a
.byte $0a, 0
fortune74:
.byte "We are MicroSoft.  You will be ",$0a
.byte "assimilated.  Resistance is futile.",$0a
.byte "(Attributed to B.G., Gill Bates)",$0a
.byte $0a, 0
fortune75:
.byte "Charm is a way of getting the answer ",$0a
.byte "Yes -- without having asked any",$0a
.byte "clear question.",$0a
.byte $0a, 0
fortune76:
.byte "I don't want to achieve immortality ",$0a
.byte "through my work.  I want to achieve",$0a
.byte "immortality through not dying.",$0a
.byte "-- Woody Allen",$0a
.byte $0a, 0
fortune77:
.byte "Disclose classified information only ",$0a
.byte "when a NEED TO KNOW exists.",$0a
.byte $0a, 0
fortune78:
.byte "He who laughs last hasn't been told ",$0a
.byte "the terrible truth.",$0a
.byte $0a, 0
fortune79:
.byte "Ten persons who speak make more noise ",$0a
.byte "than ten thousand who are silent.",$0a
.byte "-- Napoleon I",$0a
.byte $0a, 0
fortune80:
.byte "Of course you can't flap your arms and ",$0a
.byte "fly to the moon.  After a while you'd",$0a
.byte "run out of air to push against.",$0a
.byte $0a, 0
fortune81:
.byte "It's hard to tune heavily tuned code.  ",$0a
.byte ":-)",$0a
.byte "-- Larry Wall in ",$0a
.byte "<199801141725.JAA07555@wall.org>",$0a
.byte $0a, 0
fortune82:
.byte "Motorized vehicles only.",$0a
.byte $0a, 0
fortune83:
.byte "Maybe it's time to break that.",$0a
.byte "-- Larry Wall in ",$0a
.byte "<199710311718.JAA19082@wall.org>",$0a
.byte $0a, 0
fortune84:
.byte "Of all the animals, the boy is the ",$0a
.byte "most unmanageable.",$0a
.byte "-- Plato",$0a
.byte $0a, 0
fortune85:
.byte "*** Knghtbrd is now known as ",$0a
.byte "SirKewLDooD",$0a
.byte "*** Mercury kicked SirKewlDooD from ",$0a
.byte "#quakeforge (*WHACK*)",$0a
.byte $0a, 0
fortune86:
.byte "Someday you'll get your big chance -- ",$0a
.byte "or have you already had it?",$0a
.byte $0a, 0
fortune87:
.byte "Finagle's Seventh Law:",$0a
.byte "The perversity of the universe ",$0a
.byte "tends toward a maximum.",$0a
.byte $0a, 0
fortune88:
.byte "A sine curve goes off to infinity, or ",$0a
.byte "at least the end of the blackboard.",$0a
.byte "-- Prof. Steiner",$0a
.byte $0a, 0
fortune89:
.byte "If God had wanted us to be concerned ",$0a
.byte "for the plight of the toads, he would",$0a
.byte "have made them cute and furry.",$0a
.byte "-- Dave Barry",$0a
.byte $0a, 0
fortune90:
.byte "I've seen the forgeries I've sent ",$0a
.byte "out.",$0a
.byte "-- John F. Haugh II ",$0a
.byte "(jfh@rpp386.Dallas.TX.US), about ",$0a
.byte "forging net news articles",$0a
.byte $0a, 0
fortune91:
.byte "The sooner our happiness together ",$0a
.byte "begins, the longer it will last.",$0a
.byte "-- Miramanee, The ",$0a
.byte "Paradise Syndrome, stardate 4842.6",$0a
.byte $0a, 0
fortune92:
.byte "The value of a program is proportional ",$0a
.byte "to the weight of its output.",$0a
.byte $0a, 0
fortune93:
.byte "Oh, wait, that was ",$0a
.byte "Randal...nevermind...",$0a
.byte "-- Larry Wall in ",$0a
.byte "<199709261754.KAA23761@wall.org>",$0a
.byte $0a, 0
fortune94:
.byte "Hi!  I'm Larry.  This is my brother ",$0a
.byte "Bob, and this is my other brother",$0a
.byte "Jimbo.  We thought you might like to ",$0a
.byte "know the names of your assailants.",$0a
.byte $0a, 0
fortune95:
.byte "Computer programs expand so as to fill ",$0a
.byte "the core available.",$0a
.byte $0a, 0
fortune96:
.byte "If we don't survive, we don't do ",$0a
.byte "anything else.",$0a
.byte "-- John Sinclair",$0a
.byte $0a, 0
fortune97:
.byte "Don't let your mind wander -- it's too ",$0a
.byte "little to be let out alone.",$0a
.byte $0a, 0
fortune98:
.byte "1: No code table for op: ++post",$0a
.byte $0a, 0
fortune99:
.byte "Processed at location stamped in code ",$0a
.byte "at top of carton.",$0a
.byte $0a, 0
fortune100:
.byte "manic-depressive, adj.:",$0a
.byte "Easy glum, easy glow.",$0a
.byte $0a, 0
fortune101:
.byte "Remark of Dr. Baldwin's concerning ",$0a
.byte "upstarts: We don't care to eat ",$0a
.byte "toadstools",$0a
.byte "that think they are truffles.",$0a
.byte "-- Mark Twain, ",$0a
.byte "Pudd'nhead Wilson's Calendar",$0a
.byte $0a, 0
fortune102:
.byte "Life is not for everyone.",$0a
.byte $0a, 0
fortune103:
.byte "Sometimes even to live is an act of ",$0a
.byte "courage.",$0a
.byte "-- Seneca",$0a
.byte $0a, 0
fortune104:
.byte "<_Anarchy_> acf: maybe April 1 next ",$0a
.byte "year slashdot needs to run Rob Malda",$0a
.byte "            accepts new job as head of ",$0a
.byte "Debian project 8)",$0a
.byte $0a, 0
fortune105:
.byte "To teach is to learn twice.",$0a
.byte "-- Joseph Joubert",$0a
.byte $0a, 0
fortune106:
.byte "Since when has the purpose of debian ",$0a
.byte "been to appease the interests of the",$0a
.byte "mass of unskilled consumers?        -- ",$0a
.byte "Steve Shorter",$0a
.byte $0a, 0
fortune107:
.byte "Natural laws have no pity.",$0a
.byte $0a, 0
fortune108:
.byte "Let us live!!!",$0a
.byte "Let us love!!!",$0a
.byte "Let us share the deepest secrets of ",$0a
.byte "our souls!!!",$0a
.byte "",$0a
.byte "You first.",$0a
.byte $0a, 0
fortune109:
.byte "BOFH excuse #184:",$0a
.byte "",$0a
.byte "loop found in loop in redundant ",$0a
.byte "loopback",$0a
.byte $0a, 0
fortune110:
.byte "Motorized vehicles only.",$0a
.byte $0a, 0
fortune111:
.byte "A woman forgives the audacity of which ",$0a
.byte "her beauty has prompted us to be ",$0a
.byte "guilty.",$0a
.byte "-- LeSage",$0a
.byte $0a, 0
fortune112:
.byte "The distinction between true and false ",$0a
.byte "appears to become increasingly",$0a
.byte "blurred by... the pollution of the ",$0a
.byte "language.",$0a
.byte "-- Arne Tiselius",$0a
.byte $0a, 0
fortune113:
.byte "Karmageddon:",$0a
.byte "It's like, when everybody is ",$0a
.byte "sending off all these really bad",$0a
.byte "vibes, right? And then, like, the ",$0a
.byte "Earth explodes and it's like, a",$0a
.byte "serious bummer.",$0a
.byte $0a, 0
fortune114:
.byte "There are a lot of lies going ",$0a
.byte "around.... and half of them are true.",$0a
.byte "-- Winston Churchill",$0a
.byte $0a, 0
fortune115:
.byte "volcano, n.:",$0a
.byte "A mountain with hiccups.",$0a
.byte $0a, 0
fortune116:
.byte "BOFH excuse #219:",$0a
.byte "",$0a
.byte "Recursivity.  Call back if it happens ",$0a
.byte "again.",$0a
.byte $0a, 0
fortune117:
.byte "The party adjourned to a hot tub, yes. ",$0a
.byte " Fully clothed, I might add.",$0a
.byte "-- IBM employee, ",$0a
.byte "testifying in California State Supreme ",$0a
.byte "Court",$0a
.byte $0a, 0
fortune118:
.byte "BOFH excuse #221:",$0a
.byte "",$0a
.byte "The mainframe needs to rest.  It's ",$0a
.byte "getting old, you know.",$0a
.byte $0a, 0
fortune119:
.byte "Williams and Holland's Law:",$0a
.byte "If enough data is collected, ",$0a
.byte "anything may be proven by statistical",$0a
.byte "methods.",$0a
.byte $0a, 0
fortune120:
.byte "It's like deja vu all over again.",$0a
.byte "-- Yogi Berra",$0a
.byte $0a, 0
fortune121:
.byte "Chef, n.:",$0a
.byte "Any cook who swears in French.",$0a
.byte $0a, 0
fortune122:
.byte "BOFH excuse #142:",$0a
.byte "",$0a
.byte "new guy cross-connected phone lines ",$0a
.byte "with ac power bus.",$0a
.byte $0a, 0
fortune123:
.byte "BOFH excuse #147:",$0a
.byte "",$0a
.byte "Party-bug in the Aloha protocol.",$0a
.byte $0a, 0
fortune124:
.byte "  His honour rooted in dishonour stood,",$0a
.byte "  And faith unfaithful kept him ",$0a
.byte "falsely true.",$0a
.byte "-- Alfred Lord Tennyson",$0a
.byte $0a, 0
fortune125:
.byte "The solution to a problem changes the ",$0a
.byte "nature of the problem.",$0a
.byte "-- Peer",$0a
.byte $0a, 0
fortune126:
.byte "Finality is death.",$0a
.byte "Perfection is finality.",$0a
.byte "Nothing is perfect.",$0a
.byte "There are lumps in it.",$0a
.byte $0a, 0
fortune127:
.byte "They are called computers simply ",$0a
.byte "because computation is the only ",$0a
.byte "significant",$0a
.byte "job that has so far been given to them.",$0a
.byte $0a, 0
fortune128:
.byte "Those who claim the dead never return ",$0a
.byte "to life haven't ever been around",$0a
.byte "here at quitting time.",$0a
.byte $0a, 0
fortune129:
.byte "For fast-acting relief, try slowing ",$0a
.byte "down.",$0a
.byte $0a, 0
fortune130:
.byte "In the Halls of Justice the only ",$0a
.byte "justice is in the halls.",$0a
.byte "-- Lenny Bruce",$0a
.byte $0a, 0
fortune131:
.byte "The two most beautiful words in the ",$0a
.byte "English language are Cheque Enclosed.",$0a
.byte "-- Dorothy Parker",$0a
.byte $0a, 0
fortune132:
.byte "Tempt not a desperate man.",$0a
.byte "-- William ",$0a
.byte "Shakespeare, Romeo and Juliet",$0a
.byte $0a, 0
fortune133:
.byte "The best book on programming for the ",$0a
.byte "layman is Alice in Wonderland;",$0a
.byte "but that's because it's the best book ",$0a
.byte "on anything for the layman.",$0a
.byte $0a, 0
fortune134:
.byte "Tempt not a desperate man.",$0a
.byte "-- William ",$0a
.byte "Shakespeare, Romeo and Juliet",$0a
.byte $0a, 0
fortune135:
.byte "So little time, so little to do.",$0a
.byte "-- Oscar Levant",$0a
.byte $0a, 0
fortune136:
.byte "Results vary by individual.",$0a
.byte $0a, 0
fortune137:
.byte "In a gathering of two or more people, ",$0a
.byte "when a lighted cigarette is",$0a
.byte "placed in an ashtray, the smoke will ",$0a
.byte "waft into the face of the non-smoker.",$0a
.byte $0a, 0
fortune138:
.byte "When I works, I works hard.",$0a
.byte "When I sits, I sits easy.",$0a
.byte "And when I thinks, I goes to sleep.",$0a
.byte $0a, 0
fortune139:
.byte "When a girl marries she exchanges the ",$0a
.byte "attentions of many men for the",$0a
.byte "inattentions of one.",$0a
.byte "-- Helen Rowland",$0a
.byte $0a, 0
fortune140:
.byte "<knghtbrd> He's a about half the size ",$0a
.byte "of the others.",$0a
.byte "<knghtbrd> But he's got a chainsaw.",$0a
.byte $0a, 0
fortune141:
.byte "Boys, you have ALL been selected to ",$0a
.byte "LEAVE th' PLANET in 15 minutes!!",$0a
.byte $0a, 0
fortune142:
.byte "He who laughs last -- missed the punch ",$0a
.byte "line.",$0a
.byte $0a, 0
fortune143:
.byte "If people are good only because they ",$0a
.byte "fear punishment, and hope for reward,",$0a
.byte "then we are a sorry lot indeed.",$0a
.byte "-- Albert Einstein",$0a
.byte $0a, 0
fortune144:
.byte "You are a very redundant person, ",$0a
.byte "that's what kind of person you are.",$0a
.byte $0a, 0
fortune145:
.byte "I prefer rogues to imbeciles because ",$0a
.byte "they sometimes take a rest.",$0a
.byte "-- Alexandre Dumas, ",$0a
.byte "fils",$0a
.byte $0a, 0
fortune146:
.byte "A child of five could understand this! ",$0a
.byte " Fetch me a child of five.",$0a
.byte $0a, 0
fortune147:
.byte "Every journalist has a novel in him, ",$0a
.byte "which is an excellent place for it.",$0a
.byte $0a, 0
fortune148:
.byte "If you had any brains, you'd be ",$0a
.byte "dangerous.",$0a
.byte $0a, 0
fortune149:
.byte "Life is like a sewer.  What you get ",$0a
.byte "out of it depends on what you put into ",$0a
.byte "it.",$0a
.byte "-- Tom Lehrer",$0a
.byte $0a, 0
fortune150:
.byte "It's fabulous!  We haven't seen ",$0a
.byte "anything like it in the last half an ",$0a
.byte "hour!",$0a
.byte "-- Macy's",$0a
.byte $0a, 0
fortune151:
.byte "Test-tube babies shouldn't throw ",$0a
.byte "stones.",$0a
.byte $0a, 0
fortune152:
.byte "You have only to mumble a few words in ",$0a
.byte "church to get married and few words",$0a
.byte "in your sleep to get divorced.",$0a
.byte $0a, 0
fortune153:
.byte "A private sin is not so prejudicial in ",$0a
.byte "the world as a public indecency.",$0a
.byte "-- Miguel de Cervantes",$0a
.byte $0a, 0
fortune154:
.byte "The trouble with being punctual is ",$0a
.byte "that nobody's there to appreciate it.",$0a
.byte "-- Franklin P. Jones",$0a
.byte $0a, 0
fortune155:
.byte "It is easier to port a shell than a ",$0a
.byte "shell script.",$0a
.byte "-- Larry Wall",$0a
.byte $0a, 0
fortune156:
.byte "  I marvel at the strength of human ",$0a
.byte "weakness.",$0a
.byte $0a, 0
fortune157:
.byte "Finagle's Seventh Law:",$0a
.byte "The perversity of the universe ",$0a
.byte "tends toward a maximum.",$0a
.byte $0a, 0
fortune158:
.byte "Shame is an improper emotion invented ",$0a
.byte "by pietists to oppress the human race.",$0a
.byte "-- Robert Preston, ",$0a
.byte "Toddy, Victor/Victoria",$0a
.byte $0a, 0
fortune159:
.byte "SCCS, the source motel!  Programs ",$0a
.byte "check in and never check out!",$0a
.byte "-- Ken Thompson",$0a
.byte $0a, 0
fortune160:
.byte "<Xavvy> is that really knghtbrd?",$0a
.byte "<Knghtbrd> No, I'm an EVIL IMPOSTOR!",$0a
.byte "<Knghtbrd> An evil impostor who LIKES ",$0a
.byte "HYBRID!",$0a
.byte "<Xavvy> haha",$0a
.byte "<Xavvy> ok, it's him :P",$0a
.byte $0a, 0
fortune161:
.byte "nolo contendere:",$0a
.byte "A legal term meaning: I ",$0a
.byte "didn't do it, judge, and I'll never do",$0a
.byte "it again.",$0a
.byte $0a, 0
fortune162:
.byte "I never vote for anyone.  I always ",$0a
.byte "vote against.",$0a
.byte "-- W. C. Fields",$0a
.byte $0a, 0
fortune163:
.byte "Graduate life: It's not just a job.  ",$0a
.byte "It's an indenture.",$0a
.byte $0a, 0
fortune164:
.byte "First Law of Socio-Genetics:",$0a
.byte "Celibacy is not hereditary.",$0a
.byte $0a, 0
fortune165:
.byte "The only difference between a rut and ",$0a
.byte "a grave is their dimensions.",$0a
.byte $0a, 0
fortune166:
.byte "Cats are smarter than dogs.  You can't ",$0a
.byte "make eight cats pull a sled through",$0a
.byte "the snow.",$0a
.byte $0a, 0
fortune167:
.byte "Not responsible for typographical ",$0a
.byte "errors.",$0a
.byte $0a, 0
fortune168:
.byte "You may my glories and my state ",$0a
.byte "dispose,",$0a
.byte "But not my griefs; still am I king of ",$0a
.byte "those.",$0a
.byte "-- William ",$0a
.byte "Shakespeare, Richard II",$0a
.byte $0a, 0
fortune169:
.byte "I watch television because you don't ",$0a
.byte "know what it will do if you leave it",$0a
.byte "in the room alone.",$0a
.byte $0a, 0
fortune170:
.byte "BOFH excuse #33:",$0a
.byte "",$0a
.byte "piezo-electric interference",$0a
.byte $0a, 0
fortune171:
.byte "Whatever became of eternal truth?",$0a
.byte $0a, 0
fortune172:
.byte "Never ascribe to malice that which is ",$0a
.byte "caused by greed and ignorance.",$0a
.byte "-- Cal Keegan",$0a
.byte $0a, 0
fortune173:
.byte "We are using Linux daily to UP our ",$0a
.byte "productivity - so UP yours!",$0a
.byte "-- Adapted from Pat ",$0a
.byte "Paulsen by Joe Sloan",$0a
.byte $0a, 0
fortune174:
.byte "God is dead and I don't feel all too ",$0a
.byte "well either....",$0a
.byte "-- Ralph Moonen",$0a
.byte $0a, 0
fortune175:
.byte "Friends, n.:",$0a
.byte "People who borrow your books ",$0a
.byte "and set wet glasses on them.",$0a
.byte "",$0a
.byte "People who know you well, but ",$0a
.byte "like you anyway.",$0a
.byte $0a, 0
fortune176:
.byte "I'd like MY data-base JULIENNED and ",$0a
.byte "stir-fried!",$0a
.byte $0a, 0
fortune177:
.byte "hipatitis:",$0a
.byte "Terminal coolness.",$0a
.byte $0a, 0
fortune178:
.byte "I can relate to that.",$0a
.byte $0a, 0
fortune179:
.byte "Halley's Comet: It came, we saw, we ",$0a
.byte "drank.",$0a
.byte $0a, 0
fortune180:
.byte "Still looking for the glorious results ",$0a
.byte "of my misspent youth.  Say, do you",$0a
.byte "have a map to the next joint?",$0a
.byte $0a, 0
fortune181:
.byte "Bus error -- driver executed.",$0a
.byte $0a, 0
fortune182:
.byte "QOTD:",$0a
.byte "I thought I saw a unicorn on ",$0a
.byte "the way over, but it was just a",$0a
.byte "horse with one of the horns ",$0a
.byte "broken off.",$0a
.byte $0a, 0
fortune183:
.byte "Schmidt's Observation:",$0a
.byte "All things being equal, a fat ",$0a
.byte "person uses more soap",$0a
.byte "than a thin person.",$0a
.byte $0a, 0
fortune184:
.byte "Beauty:",$0a
.byte "What's in your eye when you ",$0a
.byte "have a bee in your hand.",$0a
.byte $0a, 0
fortune185:
.byte ">Ever heard of .cshrc?",$0a
.byte "That's a city in Bosnia.  Right?",$0a
.byte "-- Discussion in ",$0a
.byte "comp.os.linux.misc on the ",$0a
.byte "intuitiveness of commands",$0a
.byte $0a, 0
fortune186:
.byte "If it smells it's chemistry, if it ",$0a
.byte "crawls it's biology, if it doesn't work",$0a
.byte "it's physics.",$0a
.byte $0a, 0
fortune187:
.byte "The only problem with being a man of ",$0a
.byte "leisure is that you can never stop",$0a
.byte "and take a rest.",$0a
.byte $0a, 0
fortune188:
.byte "  This report is filled with omissions.",$0a
.byte $0a, 0
fortune189:
.byte "The rule on staying alive as a ",$0a
.byte "forecaster is to give 'em a number or",$0a
.byte "give 'em a date, but never give 'em ",$0a
.byte "both at once.",$0a
.byte "-- Jane Bryant Quinn",$0a
.byte $0a, 0
fortune190:
.byte "<Palisade> how are we going to ",$0a
.byte "pronounce '00 or '01 or '02 and so on?",$0a
.byte "<Deek> Say goodbye to the nineties, ",$0a
.byte "say hello to the naughties. :)",$0a
.byte $0a, 0
fortune191:
.byte "Non-Determinism is not meant to be ",$0a
.byte "reasonable.",$0a
.byte "-- M. J. 0'Donnell",$0a
.byte $0a, 0
fortune192:
.byte "I will make no bargains with ",$0a
.byte "terrorist hardware.",$0a
.byte "-- Peter da Silva",$0a
.byte $0a, 0
fortune193:
.byte "For three days after death hair and ",$0a
.byte "fingernails continue to grow but",$0a
.byte "phone calls taper off.",$0a
.byte "-- Johnny Carson",$0a
.byte $0a, 0
fortune194:
.byte "Here at the Phone Company, we serve ",$0a
.byte "all kinds of people; from",$0a
.byte "Presidents and Kings to the scum of ",$0a
.byte "the earth ...",$0a
.byte $0a, 0
fortune195:
.byte "Eisenhower!!  Your mimeograph machine ",$0a
.byte "upsets my stomach!!",$0a
.byte $0a, 0
fortune196:
.byte "A pencil with no point needs no eraser.",$0a
.byte $0a, 0
fortune197:
.byte "The greatest of faults is to be ",$0a
.byte "conscious of none.",$0a
.byte $0a, 0
fortune198:
.byte "Send your questions to ``ASK ZIPPY'', ",$0a
.byte "Box 40474, San Francisco, CA",$0a
.byte "94140, USA",$0a
.byte $0a, 0
fortune199:
.byte "Kissing your hand may make you feel ",$0a
.byte "very good, but a diamond and",$0a
.byte "sapphire bracelet lasts for ever.",$0a
.byte "-- Anita Loos, ",$0a
.byte "Gentlemen Prefer Blondes",$0a
.byte $0a, 0
fortune200:
.byte "BOFH excuse #281:",$0a
.byte "",$0a
.byte "The co-locator cannot verify the ",$0a
.byte "frame-relay gateway to the ISDN server.",$0a
.byte $0a, 0
fortune201:
.byte "An authority is a person who can tell ",$0a
.byte "you more about something than you",$0a
.byte "really care to know.",$0a
.byte $0a, 0
fortune202:
.byte "On the Internet, no one knows you're ",$0a
.byte "using Windows NT",$0a
.byte "-- Submitted by Ramiro ",$0a
.byte "Estrugo, restrugo@fateware.com",$0a
.byte $0a, 0
fortune203:
.byte "I knew one thing: as soon as anyone ",$0a
.byte "said you didn't need a gun, you'd ",$0a
.byte "better",$0a
.byte "take one along that worked.",$0a
.byte "-- Raymond Chandler",$0a
.byte $0a, 0
fortune204:
.byte "Seize the day, put no trust in the ",$0a
.byte "morrow!",$0a
.byte "-- Quintus Horatius ",$0a
.byte "Flaccus (Horace)",$0a
.byte $0a, 0
fortune205:
.byte "Never frighten a small man -- he'll ",$0a
.byte "kill you.",$0a
.byte $0a, 0
fortune206:
.byte "Some of my readers ask me what a ",$0a
.byte "Serial Port is.",$0a
.byte "The answer is: I don't know.",$0a
.byte "Is it some kind of wine you have with ",$0a
.byte "breakfast?",$0a
.byte $0a, 0
fortune207:
.byte "Deprive a mirror of its silver and ",$0a
.byte "even the Czar won't see his face.",$0a
.byte $0a, 0
fortune208:
.byte "<BenC> cerb: we subscribed you to ",$0a
.byte "debian-fight as the moderator",$0a
.byte "<BenC> cerb: list rules are, 1) no ",$0a
.byte "nice emails, 2) no apologies",$0a
.byte $0a, 0
fortune209:
.byte "Multics is security spelled sideways.",$0a
.byte $0a, 0
fortune210:
.byte "COBOL is for morons.",$0a
.byte "-- E. W. Dijkstra",$0a
.byte $0a, 0
fortune211:
.byte "University politics are vicious ",$0a
.byte "precisely because the stakes are so ",$0a
.byte "small.",$0a
.byte "-- C. P. Snow",$0a
.byte $0a, 0
fortune212:
.byte "Watch your mouth, kid, or you'll find ",$0a
.byte "yourself floating home.",$0a
.byte "-- Han Solo",$0a
.byte $0a, 0
fortune213:
.byte "BOFH excuse #161:",$0a
.byte "",$0a
.byte "monitor VLF leakage",$0a
.byte $0a, 0
fortune214:
.byte "I would gladly raise my voice in ",$0a
.byte "praise of women, only they won't let me",$0a
.byte "raise my voice.",$0a
.byte "-- Winkle",$0a
.byte $0a, 0
fortune215:
.byte "If in any problem you find yourself ",$0a
.byte "doing an immense amount of work, the",$0a
.byte "answer can be obtained by simple ",$0a
.byte "inspection.",$0a
.byte $0a, 0
fortune216:
.byte "Concept, n.:",$0a
.byte "Any idea for which an ",$0a
.byte "outside consultant billed you more than",$0a
.byte "$25,000.",$0a
.byte $0a, 0
fortune217:
.byte "You will attract cultured and artistic ",$0a
.byte "people to your home.",$0a
.byte $0a, 0
fortune218:
.byte "It is all right to hold a ",$0a
.byte "conversation, but you should let go of ",$0a
.byte "it",$0a
.byte "now and then.",$0a
.byte "-- Richard Armour",$0a
.byte $0a, 0
fortune219:
.byte "You have a strong appeal for members ",$0a
.byte "of your own sex.",$0a
.byte $0a, 0
fortune220:
.byte "Your love life will be... interesting.",$0a
.byte $0a, 0
fortune221:
.byte "What is worth doing is worth the ",$0a
.byte "trouble of asking somebody to do.",$0a
.byte $0a, 0
fortune222:
.byte "Marriage is the triumph of imagination ",$0a
.byte "over intelligence.  Second marriage is",$0a
.byte "the triumph of hope over experience.",$0a
.byte $0a, 0
fortune223:
.byte "PIZZA!!",$0a
.byte $0a, 0
fortune224:
.byte "AAAAAAAAAAAaaaaaaaaaaaaaaac",$0a
.byte "cccccccckkkkkk!!!!!!!!!",$0a
.byte "You brute!  Knock before entering a ",$0a
.byte "ladies room!",$0a
.byte $0a, 0
fortune225:
.byte "I'm a GENIUS!  I want to dispute ",$0a
.byte "sentence structure with SUSAN SONTAG!!",$0a
.byte $0a, 0
fortune226:
.byte "HELLO KITTY gang terrorizes town, ",$0a
.byte "family STICKERED to death!",$0a
.byte $0a, 0
fortune227:
.byte "We are drowning in information but ",$0a
.byte "starved for knowledge.",$0a
.byte "-- John Naisbitt, ",$0a
.byte "Megatrends",$0a
.byte $0a, 0
fortune228:
.byte "Let others praise ancient times; I am ",$0a
.byte "glad I was born in these.",$0a
.byte "-- Ovid (43 B.C. - ",$0a
.byte "A.D. 18)",$0a
.byte $0a, 0
fortune229:
.byte "If you wish to succeed, consult three ",$0a
.byte "old people.",$0a
.byte $0a, 0
fortune230:
.byte "This sentence contradicts itself -- no ",$0a
.byte "actually it doesn't.",$0a
.byte "-- Douglas Hofstadter",$0a
.byte $0a, 0
fortune231:
.byte "When in panic, fear and doubt,",$0a
.byte "Drink in barrels, eat, and shout.",$0a
.byte $0a, 0
fortune232:
.byte "That which is not good for the swarm, ",$0a
.byte "neither is it good for the bee.",$0a
.byte $0a, 0
fortune233:
.byte "Shedenhelm's Law:",$0a
.byte "All trails have more uphill ",$0a
.byte "sections than they have downhill ",$0a
.byte "sections.",$0a
.byte $0a, 0
fortune234:
.byte "All hope abandon, ye who enter here!",$0a
.byte "-- Dante Alighieri",$0a
.byte $0a, 0
fortune235:
.byte "BOFH excuse #404:",$0a
.byte "",$0a
.byte "Sysadmin accidentally destroyed pager ",$0a
.byte "with a large hammer.",$0a
.byte $0a, 0
fortune236:
.byte "The most important design issue... is ",$0a
.byte "the fact that Linux is supposed to",$0a
.byte "be fun...",$0a
.byte "-- Linus Torvalds at ",$0a
.byte "the First Dutch International ",$0a
.byte "Symposium on Linux",$0a
.byte $0a, 0
fortune237:
.byte "<knghtbrd> Nintendo Declares GCN Most ",$0a
.byte "Popular Console Ever",$0a
.byte "<knghtbrd> Who are they kidding?",$0a
.byte "<Mercury> knghtbrd: Stock holders?",$0a
.byte $0a, 0
fortune238:
.byte "A bird in the bush usually has a ",$0a
.byte "friend in there with him.",$0a
.byte $0a, 0
fortune239:
.byte "Better hope the life-inspector doesn't ",$0a
.byte "come around while you have your",$0a
.byte "life in such a mess.",$0a
.byte $0a, 0
fortune240:
.byte "Cinemuck, n.:",$0a
.byte "The combination of popcorn, ",$0a
.byte "soda, and melted chocolate which",$0a
.byte "covers the floors of movie ",$0a
.byte "theaters.",$0a
.byte "-- Rich Hall, ",$0a
.byte "Sniglets",$0a
.byte $0a, 0
fortune241:
.byte "You'll feel devilish tonight.  Toss ",$0a
.byte "dynamite caps under a flamenco dancer's",$0a
.byte "heel.",$0a
.byte $0a, 0
fortune242:
.byte "See label for sequence.",$0a
.byte $0a, 0
fortune243:
.byte "Fame may be fleeting but obscurity is ",$0a
.byte "forever.",$0a
.byte $0a, 0
fortune244:
.byte "The flow chart is a most thoroughly ",$0a
.byte "oversold piece of program ",$0a
.byte "documentation.",$0a
.byte "-- Frederick Brooks, ",$0a
.byte "The Mythical Man Month",$0a
.byte $0a, 0
fortune245:
.byte "History repeats itself -- the first ",$0a
.byte "time as a tragi-comedy, the second",$0a
.byte "time as bedroom farce.",$0a
.byte $0a, 0
fortune246:
.byte "Knowledge is power -- knowledge shared ",$0a
.byte "is power lost.",$0a
.byte "-- Aleister Crowley",$0a
.byte $0a, 0
fortune247:
.byte "The most difficult thing in the world ",$0a
.byte "is to know how to do a thing and to",$0a
.byte "watch someone else doing it wrong, ",$0a
.byte "without commenting.",$0a
.byte "-- T. H. White",$0a
.byte $0a, 0
fortune248:
.byte "However, never daunted, I will cope ",$0a
.byte "with adversity in my traditional",$0a
.byte "manner ... sulking and nausea.",$0a
.byte "-- Tom K. Ryan",$0a
.byte $0a, 0
fortune249:
.byte "I wish you humans would leave me alone.",$0a
.byte $0a, 0
fortune250:
.byte "In a museum in Havana, there are two ",$0a
.byte "skulls of Christopher Columbus,",$0a
.byte "one when he was a boy and one when he ",$0a
.byte "was a man.",$0a
.byte "-- Mark Twain",$0a
.byte $0a, 0
fortune251:
.byte "Contest void where prohibited by law.",$0a
.byte $0a, 0
fortune252:
.byte "When it comes to helping you, some ",$0a
.byte "people stop at nothing.",$0a
.byte $0a, 0
fortune253:
.byte "Save the bales!",$0a
.byte $0a, 0
fortune254:
.byte "Work Hard.",$0a
.byte "Rock Hard.",$0a
.byte "Eat Hard.",$0a
.byte "Sleep Hard.",$0a
.byte "Grow Big.",$0a
.byte "Wear Glasses If You Need 'Em.",$0a
.byte "-- The Webb Wilder ",$0a
.byte "Credo",$0a
.byte $0a, 0
fortune255:
.byte "You will be the last person to buy a ",$0a
.byte "Chrysler.",$0a
.byte $0a, 0
