fortune0:
.byte "Mencken and Nathan's Second Law of The Average American:",$0a
.byte "	All the postmasters in small towns read all the postcards.",$0a
.byte $0a, 0
fortune1:
.byte "If you want to make God laugh, tell him about your plans.",$0a
.byte "		-- Woody Allen",$0a
.byte $0a, 0
fortune2:
.byte "It's ten o'clock... Do you know where your AI programs are?  -- Peter Oakley",$0a
.byte $0a, 0
fortune3:
.byte "Don't tell any big lies today.  Small ones can be just as effective.",$0a
.byte $0a, 0
fortune4:
.byte "Say yur prayers, yuh flea-pickin' varmint!",$0a
.byte "		-- Yosemite Sam",$0a
.byte $0a, 0
fortune5:
.byte "What is wanted is not the will to believe, but the will to find out,",$0a
.byte "which is the exact opposite.",$0a
.byte "		-- Bertrand Russell, Skeptical Essays, 1928",$0a
.byte $0a, 0
fortune6:
.byte "If pro is the opposite of con, what is the opposite of progress?",$0a
.byte $0a, 0
fortune7:
.byte "Do not meddle in the affairs of wizards, for they become soggy and hard to",$0a
.byte "light.",$0a
.byte $0a, 0
fortune8:
.byte "BOFH excuse #166:",$0a
.byte "",$0a
.byte "/pub/lunch",$0a
.byte $0a, 0
fortune9:
.byte "When a girl marries she exchanges the attentions of many men for the",$0a
.byte "inattentions of one.",$0a
.byte "		-- Helen Rowland",$0a
.byte $0a, 0
fortune10:
.byte "i dont even know if it makes sense at all :) This is an experimental patch",$0a
.byte "for an experimental kernel :))",$0a
.byte "		-- Ingo Molnar on linux-kernel",$0a
.byte $0a, 0
fortune11:
.byte "Maj. Bloodnok:	Seagoon, you're a coward!",$0a
.byte "Seagoon:	Only in the holiday season.",$0a
.byte "Maj. Bloodnok:	Ah, another Noel Coward!",$0a
.byte $0a, 0
fortune12:
.byte "You are scrupulously honest, frank, and straightforward.  Therefore you",$0a
.byte "have few friends.",$0a
.byte $0a, 0
fortune13:
.byte "NANCY!!  Why is everything RED?!",$0a
.byte $0a, 0
fortune14:
.byte "Poland has gun control.",$0a
.byte $0a, 0
fortune15:
.byte "... but hey, this is Linux, isn't it meant to do infinite loops in 5",$0a
.byte "seconds?",$0a
.byte "		-- Jonathan Oxer in the apt-cacher ChangeLog",$0a
.byte $0a, 0
fortune16:
.byte "A bug in the code is worth two in the documentation.",$0a
.byte $0a, 0
fortune17:
.byte "I'm DESPONDENT ... I hope there's something DEEP-FRIED under this",$0a
.byte "miniature DOMED STADIUM ...",$0a
.byte $0a, 0
fortune18:
.byte "Fuch's Warning:",$0a
.byte "	If you actually look like your passport photo, you aren't well",$0a
.byte "	enough to travel.",$0a
.byte $0a, 0
fortune19:
.byte "A diplomatic husband said to his wife, How do you expect me to remember",$0a
.byte "your birthday when you never look any older?",$0a
.byte $0a, 0
fortune20:
.byte "An exotic journey in downtown Newark is in your future.",$0a
.byte $0a, 0
fortune21:
.byte "Arguments are extremely vulgar, for everyone in good society holds exactly",$0a
.byte "the same opinion.",$0a
.byte "		-- Oscar Wilde",$0a
.byte $0a, 0
fortune22:
.byte "May you live in interesting times.",$0a
.byte "		-- Chinese proverb",$0a
.byte $0a, 0
fortune23:
.byte "Men occasionally stumble over the truth, but most of them pick themselves",$0a
.byte "up and hurry off as if nothing had happened.",$0a
.byte "		-- Winston Churchill",$0a
.byte $0a, 0
fortune24:
.byte "Ogden's Law:",$0a
.byte "	The sooner you fall behind, the more time you have to catch up.",$0a
.byte $0a, 0
fortune25:
.byte "When someone says I want a programming language in which I need only",$0a
.byte "say what I wish done, give him a lollipop.",$0a
.byte $0a, 0
fortune26:
.byte "You may already be a loser.",$0a
.byte "		-- Form letter received by Rodney Dangerfield.",$0a
.byte $0a, 0
fortune27:
.byte "I love ROCK 'N ROLL!  I memorized the all WORDS to WIPE-OUT in",$0a
.byte "1965!!",$0a
.byte $0a, 0
fortune28:
.byte "Matrimony isn't a word, it's a sentence.",$0a
.byte $0a, 0
fortune29:
.byte "All my friends are getting married,",$0a
.byte "Yes, they're all growing old,",$0a
.byte "They're all staying home on the weekend,",$0a
.byte "They're all doing what they're told.",$0a
.byte $0a, 0
fortune30:
.byte "Spectacularism:",$0a
.byte "	A fascination with extreme situations.",$0a
.byte "		-- Douglas Coupland, Generation X: Tales for an Accelerated",$0a
.byte "		   Culture",$0a
.byte $0a, 0
fortune31:
.byte "Q:	What do you get when you cross the Godfather with an attorney?",$0a
.byte "A:	An offer you can't understand.",$0a
.byte $0a, 0
fortune32:
.byte "Short people get rained on last.",$0a
.byte $0a, 0
fortune33:
.byte "I'm going to raise an issue and stick it in your ear.",$0a
.byte "		-- John Foreman",$0a
.byte $0a, 0
fortune34:
.byte "You are a very redundant person, that's what kind of person you are.",$0a
.byte $0a, 0
fortune35:
.byte "The Universe is populated by stable things.",$0a
.byte "		-- Richard Dawkins",$0a
.byte $0a, 0
fortune36:
.byte "Sleep -- the most beautiful experience in life -- except drink.",$0a
.byte "		-- W. C. Fields",$0a
.byte $0a, 0
fortune37:
.byte "All life evolves by the differential survival of replicating entities.",$0a
.byte "		-- Dawkins",$0a
.byte $0a, 0
fortune38:
.byte "Young men think old men are fools; but old men know young men are fools.",$0a
.byte "		-- George Chapman",$0a
.byte $0a, 0
fortune39:
.byte ":-) your own self.",$0a
.byte "		-- Larry Wall in <199709261754.KAA23761@wall.org>",$0a
.byte $0a, 0
fortune40:
.byte "<Chalky> gcc is the best compressor ever ported to linux. it can turn",$0a
.byte "         12MB of kernel source (and that's .debbed) into a 500k kernel",$0a
.byte $0a, 0
fortune41:
.byte "In any formula, constants (especially those obtained from handbooks)",$0a
.byte "are to be treated as variables.",$0a
.byte $0a, 0
fortune42:
.byte "Pardon me, but do you know what it means to be TRULY ONE with your BOOTH!",$0a
.byte $0a, 0
fortune43:
.byte "Turn on, tune up, rock out.",$0a
.byte "		-- Billy Gibbons",$0a
.byte $0a, 0
fortune44:
.byte "Say yur prayers, yuh flea-pickin' varmint!",$0a
.byte "		-- Yosemite Sam",$0a
.byte $0a, 0
fortune45:
.byte "That money talks,",$0a
.byte "I'll not deny,",$0a
.byte "I heard it once,",$0a
.byte "It said Good-bye.",$0a
.byte "		-- Richard Armour",$0a
.byte $0a, 0
fortune46:
.byte "But what can you do with it?",$0a
.byte "		-- ubiquitous cry from Linux-user partner",$0a
.byte $0a, 0
fortune47:
.byte "...though his invention worked superbly -- his theory was a crock of sewage from",$0a
.byte "beginning to end. -- Vernor Vinge, The Peace War",$0a
.byte $0a, 0
fortune48:
.byte "Weinberg's Principle:",$0a
.byte "	An expert is a person who avoids the small errors while",$0a
.byte "	sweeping on to the grand fallacy.",$0a
.byte $0a, 0
fortune49:
.byte "Life is a healthy respect for mother nature laced with greed.",$0a
.byte $0a, 0
fortune50:
.byte "The more data I punch in this card, the lighter it becomes, and the",$0a
.byte "lower the mailing cost.",$0a
.byte "		-- S. Kelly-Bootle, The Devil's DP Dictionary",$0a
.byte $0a, 0
fortune51:
.byte "Outside of a dog, a book is man's best friend.  Inside of a dog, it is too",$0a
.byte "dark to read.",$0a
.byte $0a, 0
fortune52:
.byte "This generation may be the one that will face Armageddon.",$0a
.byte "		-- Ronald Reagan, People magazine, December 26, 1985",$0a
.byte $0a, 0
fortune53:
.byte "A beginning is the time for taking the most delicate care that balances are",$0a
.byte "correct.",$0a
.byte "		-- Princess Irulan, Manual of Maud'Dib",$0a
.byte $0a, 0
fortune54:
.byte "Cogito cogito ergo cogito sum --",$0a
.byte "I think that I think, therefore I think that I am.",$0a
.byte "		-- Ambrose Bierce, The Devil's Dictionary",$0a
.byte $0a, 0
fortune55:
.byte "Can anything be sadder than work left unfinished? Yes, work never begun.",$0a
.byte $0a, 0
fortune56:
.byte "Once you've tried to change the world you find it's a whole bunch easier",$0a
.byte "to change your mind.",$0a
.byte $0a, 0
fortune57:
.byte "How many teamsters does it take to screw in a light bulb?",$0a
.byte "   FIFTEEN!!  YOU GOT A PROBLEM WITH THAT?",$0a
.byte $0a, 0
fortune58:
.byte "What awful irony is this?",$0a
.byte "We are as gods, but know it not.",$0a
.byte $0a, 0
fortune59:
.byte "Question authority.",$0a
.byte $0a, 0
fortune60:
.byte "When you have an efficient government, you have a dictatorship.",$0a
.byte "		-- Harry Truman",$0a
.byte $0a, 0
fortune61:
.byte "You want to know why I kept getting promoted?  Because my mouth knows more",$0a
.byte "than my brain.",$0a
.byte "		-- W.G.",$0a
.byte $0a, 0
fortune62:
.byte "The test of intelligent tinkering is to save all the parts.",$0a
.byte "		-- Aldo Leopold",$0a
.byte $0a, 0
fortune63:
.byte "<Knghtbrd> This font is starting to come out very nicely",$0a
.byte "<stu> Knghtbrd: oh dear, are you hacking up another quake font in vi? :)",$0a
.byte $0a, 0
fortune64:
.byte "I give you the man who -- the man who -- uh, I forgets the man who?",$0a
.byte "		-- Beauregard Bugleboy",$0a
.byte $0a, 0
fortune65:
.byte "Indifference will certainly be the downfall of mankind, but who cares?",$0a
.byte $0a, 0
fortune66:
.byte "The secret of happiness is total disregard of everybody.",$0a
.byte $0a, 0
fortune67:
.byte "Immanuel doesn't pun, he Kant.",$0a
.byte $0a, 0
fortune68:
.byte "Tis man's perdition to be safe, when for the truth he ought to die.",$0a
.byte $0a, 0
fortune69:
.byte "I'm in direct contact with many advanced fun CONCEPTS.",$0a
.byte $0a, 0
fortune70:
.byte "Absence makes the heart grow frantic.",$0a
.byte $0a, 0
fortune71:
.byte "Do Miami a favor.  When you leave, take someone with you.",$0a
.byte $0a, 0
fortune72:
.byte "O, what a tangled web we weave, When first we practice to deceive.",$0a
.byte "		-- Sir Walter Scott, Marmion",$0a
.byte $0a, 0
fortune73:
.byte "Girls who throw themselves at men, are actually taking very careful aim.",$0a
.byte $0a, 0
fortune74:
.byte "Boycott meat -- suck your thumb.",$0a
.byte $0a, 0
fortune75:
.byte "How do I get HOME?",$0a
.byte $0a, 0
fortune76:
.byte "Be careful of reading health books, you might die of a misprint.",$0a
.byte "		-- Mark Twain",$0a
.byte $0a, 0
fortune77:
.byte "Q:	What is purple and conquered the world?",$0a
.byte "A:	Alexander the Grape.",$0a
.byte $0a, 0
fortune78:
.byte "A shapely CATHOLIC SCHOOLGIRL is FIDGETING inside my costume..",$0a
.byte $0a, 0
fortune79:
.byte "Now I can finally explain to everyone why I do this.  I just got $7 worth",$0a
.byte "of free stuff for working on Debian !",$0a
.byte $0a, 0
fortune80:
.byte "Are you ever going to do the dishes?  Or will you change your major to biology?",$0a
.byte $0a, 0
fortune81:
.byte "The easiest way to figure the cost of living is to take your income and",$0a
.byte "add ten percent.",$0a
.byte $0a, 0
fortune82:
.byte "A committee takes root and grows, it flowers, wilts and dies, scattering the",$0a
.byte "seed from which other committees will bloom.",$0a
.byte "		-- Parkinson",$0a
.byte $0a, 0
fortune83:
.byte "Time as he grows old teaches all things.",$0a
.byte "		-- Aeschylus",$0a
.byte $0a, 0
fortune84:
.byte "The universe is like a safe to which there is a combination -- but the",$0a
.byte "combination is locked up in the safe.",$0a
.byte "		-- Peter DeVries",$0a
.byte $0a, 0
fortune85:
.byte "Whoever would lie usefully should lie seldom.",$0a
.byte $0a, 0
fortune86:
.byte "You need tender loving care once a week - so that I can slap you into shape.",$0a
.byte "		-- Ellyn Mustard",$0a
.byte $0a, 0
fortune87:
.byte "Kites rise highest against the wind -- not with it.",$0a
.byte "		-- Winston Churchill",$0a
.byte $0a, 0
fortune88:
.byte "The whole problem with the world is that fools and fanatics are always so",$0a
.byte "certain of themselves, but wiser people so full of doubts.",$0a
.byte "		-- Bertrand Russell",$0a
.byte $0a, 0
fortune89:
.byte "You can't have filenames longer than 14 chars.",$0a
.byte "You can't even think about them!",$0a
.byte "		-- Larry Wall in Configure from the perl distribution",$0a
.byte $0a, 0
fortune90:
.byte "When among apes, one must play the ape.",$0a
.byte $0a, 0
fortune91:
.byte "You will be aided greatly by a person whom you thought to be unimportant.",$0a
.byte $0a, 0
fortune92:
.byte "I'm so miserable without you, it's almost like you're here.",$0a
.byte $0a, 0
fortune93:
.byte "I'd love to go out with you, but I'm converting my calendar watch from",$0a
.byte "Julian to Gregorian.",$0a
.byte $0a, 0
fortune94:
.byte "Q:	Why do firemen wear red suspenders?",$0a
.byte "A:	To conform with departmental regulations concerning uniform dress.",$0a
.byte $0a, 0
fortune95:
.byte "Patience is a minor form of despair, disguised as virtue.",$0a
.byte "		-- Ambrose Bierce, on qualifiers",$0a
.byte $0a, 0
fortune96:
.byte "Thirteen at a table is unlucky only when the hostess has only twelve chops.",$0a
.byte "		-- Groucho Marx",$0a
.byte $0a, 0
fortune97:
.byte "I cannot draw a cart, nor eat dried oats; If it be man's work I will do it.",$0a
.byte $0a, 0
fortune98:
.byte "consultant, n.:",$0a
.byte "	Someone who knowns 101 ways to make love, but can't get a date.",$0a
.byte $0a, 0
fortune99:
.byte "Lord, defend me from my friends; I can account for my enemies.",$0a
.byte "		-- Charles D'Hericault",$0a
.byte $0a, 0
fortune100:
.byte "He who loses, wins the race,",$0a
.byte "And parallel lines meet in space.",$0a
.byte "		-- John Boyd, Last Starship from Earth",$0a
.byte $0a, 0
fortune101:
.byte "Chaos is King and Magic is loose in the world.",$0a
.byte $0a, 0
fortune102:
.byte "<liiwi> udp - universal dropping of an pigeon",$0a
.byte $0a, 0
fortune103:
.byte "Rules for Academic Deans:",$0a
.byte "	(1)  HIDE!!!!",$0a
.byte "	(2)  If they find you, LIE!!!!",$0a
.byte "		-- Father Damian C. Fandal",$0a
.byte $0a, 0
fortune104:
.byte "The penalty for laughing in a courtroom is six months in jail; if it",$0a
.byte "were not for this penalty, the jury would never hear the evidence.",$0a
.byte "		-- H. L. Mencken",$0a
.byte $0a, 0
fortune105:
.byte "Honesty is for the most part less profitable than dishonesty.",$0a
.byte "		-- Plato",$0a
.byte $0a, 0
fortune106:
.byte "... bleakness ... desolation ... plastic forks ...",$0a
.byte $0a, 0
fortune107:
.byte "Why must you tell me all your secrets when it's hard enough to love",$0a
.byte "you knowing nothing?",$0a
.byte "		-- Lloyd Cole and the Commotions",$0a
.byte $0a, 0
fortune108:
.byte "You are going to have a new love affair.",$0a
.byte $0a, 0
fortune109:
.byte "I never said all Democrats were saloonkeepers; what I said was all",$0a
.byte "saloonkeepers were Democrats.",$0a
.byte $0a, 0
fortune110:
.byte "Liar, n.:",$0a
.byte "	A lawyer with a roving commission.",$0a
.byte "		-- Ambrose Bierce, The Devil's Dictionary",$0a
.byte $0a, 0
fortune111:
.byte "Never put off until tomorrow what you can do today.  There might be a",$0a
.byte "law against it by that time.",$0a
.byte $0a, 0
fortune112:
.byte "You're just the sort of person I imagined marrying, when I was little...",$0a
.byte "except, y'know, not green... and without all the patches of fungus.",$0a
.byte "		-- Swamp Thing",$0a
.byte $0a, 0
fortune113:
.byte "Give me a Plumber's friend the size of the Pittsburgh dome, and a place",$0a
.byte "to stand, and I will drain the world.",$0a
.byte $0a, 0
fortune114:
.byte "Warp 7 -- It's a law we can live with.",$0a
.byte $0a, 0
fortune115:
.byte "BOFH excuse #70:",$0a
.byte "",$0a
.byte "nesting roaches shorted out the ether cable",$0a
.byte $0a, 0
fortune116:
.byte "It's there as a sop to former Ada programmers.  :-)",$0a
.byte "		-- Larry Wall regarding 10_000_000 in <11556@jpl-devvax.JPL.NASA.GOV>",$0a
.byte $0a, 0
fortune117:
.byte "Not responsible for typographical errors.",$0a
.byte $0a, 0
fortune118:
.byte "Bus error -- please leave by the rear door.",$0a
.byte $0a, 0
fortune119:
.byte "The more crap you put up with, the more crap you are going to get.",$0a
.byte $0a, 0
fortune120:
.byte "	A crow perched himself on a telephone wire.  He was going to make a",$0a
.byte "long-distance caw.",$0a
.byte $0a, 0
fortune121:
.byte "What does it mean in the sentence What time is it??",$0a
.byte $0a, 0
fortune122:
.byte "Green light in A.M. for new projects.  Red light in P.M. for traffic tickets.",$0a
.byte $0a, 0
fortune123:
.byte "And 1.1.81 is officially BugFree(tm), so if you receive any bug-reports",$0a
.byte "on it, you know they are just evil lies.",$0a
.byte "		-- Linus Torvalds",$0a
.byte $0a, 0
fortune124:
.byte "Screw up your courage!  You've screwed up everything else.",$0a
.byte $0a, 0
fortune125:
.byte "Keep refrigerated.",$0a
.byte $0a, 0
fortune126:
.byte "This Fortune Examined By INSPECTOR NO. 2-14",$0a
.byte $0a, 0
fortune127:
.byte "If I don't see you in the future, I'll see you in the pasture.",$0a
.byte $0a, 0
fortune128:
.byte "I'm still waiting for the advent of the computer science groupie.",$0a
.byte $0a, 0
fortune129:
.byte "Absinthe makes the tart grow fonder.",$0a
.byte $0a, 0
fortune130:
.byte "toilet toup'ee, n.:",$0a
.byte "	Any shag carpet that causes the lid to become top-heavy, thus",$0a
.byte "	creating endless annoyance to male users.",$0a
.byte "		-- Rich Hall, Sniglets",$0a
.byte $0a, 0
fortune131:
.byte "Time to be aggressive.  Go after a tattooed Virgo.",$0a
.byte $0a, 0
fortune132:
.byte "Who needs friends when you can sit alone in your room and drink?",$0a
.byte $0a, 0
fortune133:
.byte "Some people around here wouldn't recognize subtlety if it hit them on the head.",$0a
.byte $0a, 0
fortune134:
.byte "Today you'll start getting heavy metal radio on your dentures.",$0a
.byte $0a, 0
fortune135:
.byte "Never trust anybody whose arm is bigger than your leg.",$0a
.byte $0a, 0
fortune136:
.byte "If you give Congress a chance to vote on both sides of an issue, it",$0a
.byte "will always do it.",$0a
.byte "		-- Les Aspin, D., Wisconsin",$0a
.byte $0a, 0
fortune137:
.byte "Dr. Jekyll had something to Hyde.",$0a
.byte $0a, 0
fortune138:
.byte "Sorry.  I just realized this sentance makes no sense :)",$0a
.byte "		-- Ian Main",$0a
.byte $0a, 0
fortune139:
.byte "Class, that's the only thing that counts in life.  Class.",$0a
.byte "Without class and style, a man's a bum; he might as well be dead.",$0a
.byte "		-- Bugsy Siegel",$0a
.byte $0a, 0
fortune140:
.byte "Come quickly, I am tasting stars!",$0a
.byte "		-- Dom Perignon, upon discovering champagne.",$0a
.byte $0a, 0
fortune141:
.byte "The easiest way to figure the cost of living is to take your income and",$0a
.byte "add ten percent.",$0a
.byte $0a, 0
fortune142:
.byte "Shift to the left,",$0a
.byte "Shift to the right,",$0a
.byte "Mask in, mask out,",$0a
.byte "BYTE, BYTE, BYTE !!!",$0a
.byte $0a, 0
fortune143:
.byte "When your work speaks for itself, don't interrupt.",$0a
.byte "		-- Henry J. Kaiser",$0a
.byte $0a, 0
fortune144:
.byte "Trouble always comes at the wrong time.",$0a
.byte $0a, 0
fortune145:
.byte "Boycott meat -- suck your thumb.",$0a
.byte $0a, 0
fortune146:
.byte "I'd love to go out with you, but my favorite commercial is on TV.",$0a
.byte $0a, 0
fortune147:
.byte "Perl will always provide the null.",$0a
.byte "		-- Larry Wall in <199801151818.KAA14538@wall.org>",$0a
.byte $0a, 0
fortune148:
.byte "Better hope you get what you want before you stop wanting it.",$0a
.byte $0a, 0
fortune149:
.byte "A good man always knows his limitations.",$0a
.byte "		-- Harry Callahan",$0a
.byte $0a, 0
fortune150:
.byte "An ounce of hypocrisy is worth a pound of ambition.",$0a
.byte "		-- Michael Korda",$0a
.byte $0a, 0
fortune151:
.byte "A long memory is the most subversive idea in America.",$0a
.byte $0a, 0
fortune152:
.byte "I've always felt sorry for people that don't drink -- remember,",$0a
.byte "when they wake up, that's as good as they're gonna feel all day!",$0a
.byte $0a, 0
fortune153:
.byte "Atomic batteries to power, turbines to speed.",$0a
.byte "		-- Robin, The Boy Wonder",$0a
.byte $0a, 0
fortune154:
.byte "The early bird gets the coffee left over from the night before.",$0a
.byte $0a, 0
fortune155:
.byte "The notion of a record is an obsolete remnant of the days of the 80-column",$0a
.byte "card.",$0a
.byte "		-- Dennis M. Ritchie",$0a
.byte $0a, 0
fortune156:
.byte "BOFH excuse #184:",$0a
.byte "",$0a
.byte "loop found in loop in redundant loopback",$0a
.byte $0a, 0
fortune157:
.byte "Life is knowing how far to go without crossing the line.",$0a
.byte $0a, 0
fortune158:
.byte "FACILITY REJECTED 100044200000;",$0a
.byte $0a, 0
fortune159:
.byte "I had the rare misfortune of being one of the first people to try and",$0a
.byte "implement a PL/1 compiler.",$0a
.byte "		-- T. Cheatham",$0a
.byte $0a, 0
fortune160:
.byte "You must be the change you wish to see in the world.",$0a
.byte "		-- Mahatma Gandhi",$0a
.byte $0a, 0
fortune161:
.byte "Many people feel that if you won't let them make you happy, they'll make you",$0a
.byte "suffer.",$0a
.byte $0a, 0
fortune162:
.byte "quark:",$0a
.byte "	The sound made by a well bred duck.",$0a
.byte $0a, 0
fortune163:
.byte "Ask not what's inside your head, but what your head's inside of.",$0a
.byte "		-- J. J. Gibson",$0a
.byte $0a, 0
fortune164:
.byte "To live is always desirable.",$0a
.byte "		-- Eleen the Capellan, Friday's Child, stardate 3498.9",$0a
.byte $0a, 0
fortune165:
.byte "Good day to deal with people in high places; particularly lonely stewardesses.",$0a
.byte $0a, 0
fortune166:
.byte "I'm QUIETLY reading the latest issue of BOWLING WORLD while my wife",$0a
.byte "and two children stand QUIETLY BY ...",$0a
.byte $0a, 0
fortune167:
.byte "  This report is filled with omissions.",$0a
.byte $0a, 0
fortune168:
.byte "Somewhere in suburban Honolulu, an unemployed bellhop is whipping up a",$0a
.byte "batch of illegal psilocybin chop suey!!",$0a
.byte $0a, 0
fortune169:
.byte "The first is to ensure your partner understands that nature has root",$0a
.byte "privileges - nature doesn't have to make sense.",$0a
.byte "		-- Telsa Gwynne",$0a
.byte $0a, 0
fortune170:
.byte "You know you have a small apartment when Rice Krispies echo.",$0a
.byte "		-- S. Rickly Christian",$0a
.byte $0a, 0
fortune171:
.byte "Computers will not be perfected until they can compute how much more",$0a
.byte "than the estimate the job will cost.",$0a
.byte $0a, 0
fortune172:
.byte "Disco oil bussing will create a throbbing naugahide pipeline running",$0a
.byte "straight to the tropics from the rug producing regions and devalue the dollar!",$0a
.byte $0a, 0
fortune173:
.byte "It's important that people know what you stand for.",$0a
.byte "It's more important that they know what you won't stand for.",$0a
.byte $0a, 0
fortune174:
.byte "It's not reality or how you perceive things that's important -- it's",$0a
.byte "what you're taking for it...",$0a
.byte $0a, 0
fortune175:
.byte "A citizen of America will cross the ocean to fight for democracy, but",$0a
.byte "won't cross the street to vote in a national election.",$0a
.byte "		-- Bill Vaughan",$0a
.byte $0a, 0
fortune176:
.byte "As long as we're going to reinvent the wheel again, we might as well try making",$0a
.byte "it round this time.",$0a
.byte "		-- Mike Dennison",$0a
.byte $0a, 0
fortune177:
.byte "Don't despair; your ideal lover is waiting for you around the corner.",$0a
.byte $0a, 0
fortune178:
.byte "What's so funny?",$0a
.byte $0a, 0
fortune179:
.byte "Is knowledge knowable?  If not, how do we know that?",$0a
.byte $0a, 0
fortune180:
.byte "The future not being born, my friend, we will abstain from baptizing it.",$0a
.byte "		-- George Meredith",$0a
.byte $0a, 0
fortune181:
.byte "You shouldn't have to pay for your love with your bones and your flesh.",$0a
.byte "		-- Pat Benatar, Hell is for Children",$0a
.byte $0a, 0
fortune182:
.byte "BOFH excuse #89:",$0a
.byte "",$0a
.byte "Electromagnetic energy loss",$0a
.byte $0a, 0
fortune183:
.byte "finlandia:~> apropos win",$0a
.byte "win: nothing appropriate.",$0a
.byte $0a, 0
fortune184:
.byte "If this fortune didn't exist, somebody would have invented it.",$0a
.byte $0a, 0
fortune185:
.byte "Q:	Why did the germ cross the microscope?",$0a
.byte "A:	To get to the other slide.",$0a
.byte $0a, 0
fortune186:
.byte "You can't play your friends like marks, kid.",$0a
.byte "		-- Henry Gondorf, The Sting",$0a
.byte $0a, 0
fortune187:
.byte "The price of seeking to force our beliefs on others is that someday",$0a
.byte "they might force their beliefs on us.",$0a
.byte "		-- Mario Cuomo",$0a
.byte $0a, 0
fortune188:
.byte "Many people feel that if you won't let them make you happy, they'll make you",$0a
.byte "suffer.",$0a
.byte $0a, 0
fortune189:
.byte "The smallest worm will turn being trodden on.",$0a
.byte "		-- William Shakespeare, Henry VI",$0a
.byte $0a, 0
fortune190:
.byte "Let the worthy citizens of Chicago get their liquor the best way",$0a
.byte "they can. I'm sick of the job.  It's a thankless one and full of grief.",$0a
.byte "		-- Al Capone",$0a
.byte $0a, 0
fortune191:
.byte "Macho does not prove mucho.",$0a
.byte "		-- Zsa Zsa Gabor",$0a
.byte $0a, 0
fortune192:
.byte "I allow the world to live as it chooses, and I allow myself to live as I",$0a
.byte "choose.",$0a
.byte $0a, 0
fortune193:
.byte "In Boston, it is illegal to hold frog-jumping contests in nightclubs.",$0a
.byte $0a, 0
fortune194:
.byte "Good night, Austin, Texas, wherever you are!",$0a
.byte $0a, 0
fortune195:
.byte "Serenity through viciousness.",$0a
.byte $0a, 0
fortune196:
.byte "No man is an island, but some of us are long peninsulas.",$0a
.byte $0a, 0
fortune197:
.byte "The decision doesn't have to be logical; it was unanimous.",$0a
.byte $0a, 0
fortune198:
.byte "Chef, n.:",$0a
.byte "	Any cook who swears in French.",$0a
.byte $0a, 0
fortune199:
.byte "The meek shall inherit the earth; the rest of us will go to the stars.",$0a
.byte $0a, 0
fortune200:
.byte "Alright, you!!  Imitate a WOUNDED SEAL pleading for a PARKING SPACE!!",$0a
.byte $0a, 0
fortune201:
.byte "The mosquito exists to keep the mighty humble.",$0a
.byte $0a, 0
fortune202:
.byte "Remember that whatever misfortune may be your lot, it could only be",$0a
.byte "worse in Cleveland.",$0a
.byte "		-- National Lampoon, Deteriorata",$0a
.byte $0a, 0
fortune203:
.byte "Any circuit design must contain at least one part which is obsolete, two parts",$0a
.byte "which are unobtainable, and three parts which are still under development.",$0a
.byte $0a, 0
fortune204:
.byte "I went to the museum where they had all the heads and arms from the",$0a
.byte "statues that are in all the other museums.",$0a
.byte "		-- Steven Wright",$0a
.byte $0a, 0
fortune205:
.byte "Call toll free number before digging.",$0a
.byte $0a, 0
fortune206:
.byte "The good (I am convinced, for one)",$0a
.byte "Is but the bad one leaves undone.",$0a
.byte "Once your reputation's done",$0a
.byte "You can live a life of fun.",$0a
.byte "		-- Wilhelm Busch",$0a
.byte $0a, 0
fortune207:
.byte "Raising pet electric eels is gaining a lot of current popularity.",$0a
.byte $0a, 0
fortune208:
.byte "For 20 dollars, I'll give you a good fortune next time ...",$0a
.byte $0a, 0
fortune209:
.byte "And we heard him exclaim",$0a
.byte "As he started to roam:",$0a
.byte "I'm a hologram, kids,",$0a
.byte "please don't try this at home!'",$0a
.byte "		-- Bob Violence",$0a
.byte $0a, 0
fortune210:
.byte "In my experience, if you have to keep the lavatory door shut by extending",$0a
.byte "your left leg, it's modern architecture.",$0a
.byte "		-- Nancy Banks Smith",$0a
.byte $0a, 0
fortune211:
.byte "People don't usually make the same mistake twice -- they make it three",$0a
.byte "times, four time, five times...",$0a
.byte $0a, 0
fortune212:
.byte "An honest tale speeds best being plainly told.",$0a
.byte "		-- William Shakespeare, Henry VI",$0a
.byte $0a, 0
fortune213:
.byte "There are only two kinds of tequila.  Good and better.",$0a
.byte $0a, 0
fortune214:
.byte "Every day it's the same thing -- variety.  I want something different.",$0a
.byte $0a, 0
fortune215:
.byte "I think irc isn't going to work though---we're running out of topic space!",$0a
.byte "		-- Joseph Carter",$0a
.byte $0a, 0
fortune216:
.byte "Beer & Pretzels -- Breakfast of Champions.",$0a
.byte $0a, 0
fortune217:
.byte "Asking a working writer what he thinks about critics is like asking a",$0a
.byte "lamp-post how it feels about dogs.",$0a
.byte "		-- Christopher Hampton",$0a
.byte $0a, 0
fortune218:
.byte "Sinners can repent, but stupid is forever.",$0a
.byte $0a, 0
fortune219:
.byte "Who cares if it doesn't do anything?  It was made with our new",$0a
.byte "Triple-Iso-Bifurcated-Krypton-Gate-MOS process ...",$0a
.byte $0a, 0
fortune220:
.byte "Regardless of whether a mission expands or contracts, administrative",$0a
.byte "overhead continues to grow at a steady rate.",$0a
.byte $0a, 0
fortune221:
.byte "I surely do hope that's a syntax error.",$0a
.byte "		-- Larry Wall in <199710011752.KAA21624@wall.org>",$0a
.byte $0a, 0
fortune222:
.byte "All a man needs out of life is a place to sit 'n' spit in the fire.",$0a
.byte $0a, 0
fortune223:
.byte "I just know I'm a better manager when I have Joe DiMaggio in center field.",$0a
.byte "		-- Casey Stengel",$0a
.byte $0a, 0
fortune224:
.byte "BOFH excuse #83:",$0a
.byte "",$0a
.byte "Support staff hung over, send aspirin and come back LATER.",$0a
.byte $0a, 0
fortune225:
.byte "The meek don't want it.",$0a
.byte $0a, 0
fortune226:
.byte "intaxication:",$0a
.byte "	Euphoria at getting a tax refund, which lasts until you realize",$0a
.byte "it was your money to start with.",$0a
.byte $0a, 0
fortune227:
.byte "Since when has the purpose of debian been to appease the interests of the",$0a
.byte "mass of unskilled consumers?        -- Steve Shorter",$0a
.byte $0a, 0
fortune228:
.byte "Love is an ideal thing, marriage a real thing; a confusion of the real",$0a
.byte "with the ideal never goes unpunished.",$0a
.byte "		-- Goethe",$0a
.byte $0a, 0
fortune229:
.byte "Tell the truth or trump--but get the trick.",$0a
.byte "		-- Mark Twain, Pudd'nhead Wilson's Calendar",$0a
.byte $0a, 0
fortune230:
.byte "You just wait, I'll sin till I blow up!",$0a
.byte "		-- Dylan Thomas",$0a
.byte $0a, 0
fortune231:
.byte "You have an unusual understanding of the problems of human relationships.",$0a
.byte $0a, 0
fortune232:
.byte "Logic is a pretty flower that smells bad.",$0a
.byte $0a, 0
fortune233:
.byte "Immature poets imitate, mature poets steal.",$0a
.byte "		-- T. S. Eliot, Philip Massinger",$0a
.byte $0a, 0
fortune234:
.byte "It's not the inital skirt length, it's the upcreep.",$0a
.byte $0a, 0
fortune235:
.byte "One would like to stroke and caress human beings, but one dares not do so,",$0a
.byte "because they bite.",$0a
.byte "		-- Vladimir Il'ich Lenin",$0a
.byte $0a, 0
fortune236:
.byte "Nostalgia is living life in the past lane.",$0a
.byte $0a, 0
fortune237:
.byte "Row, row, row your bits, gently down the stream...",$0a
.byte $0a, 0
fortune238:
.byte "If we were meant to get up early, God would have created us with alarm clocks.",$0a
.byte $0a, 0
fortune239:
.byte "Quite frankly, I don't like you humans.  After what you all have done,",$0a
.byte "I find being 'inhuman' a compliment.",$0a
.byte "		-- Spider Robinson, Callahan's Secret",$0a
.byte $0a, 0
fortune240:
.byte "The first rule of all intelligent tinkering is to keep all the parts.",$0a
.byte "		-- Aldo Leopold, quoted in Donald Wurster's Nature's Economy",$0a
.byte $0a, 0
fortune241:
.byte "Freedom begins when you tell Mrs. Grundy to go fly a kite.",$0a
.byte $0a, 0
fortune242:
.byte "She's learned to say things with her eyes that others waste time putting",$0a
.byte "into words.",$0a
.byte $0a, 0
fortune243:
.byte "I know not how I came into this, shall I call it a dying life or a",$0a
.byte "living death?",$0a
.byte "		-- St. Augustine",$0a
.byte $0a, 0
fortune244:
.byte "Sears has everything.",$0a
.byte $0a, 0
fortune245:
.byte "Of all men's miseries, the bitterest is this:",$0a
.byte "to know so much and have control over nothing.",$0a
.byte "		-- Herodotus",$0a
.byte $0a, 0
fortune246:
.byte "tax office, n.:",$0a
.byte "	Den of inequity.",$0a
.byte $0a, 0
fortune247:
.byte "  An Irishman is never at peace except when he's fighting.",$0a
.byte $0a, 0
fortune248:
.byte "Might as well be frank, monsieur.  It would take a miracle to get you out",$0a
.byte "of Casablanca and the Germans have outlawed miracles.",$0a
.byte "		-- Casablanca",$0a
.byte $0a, 0
fortune249:
.byte "Before destruction a man's heart is haughty, but humility goes before honour.",$0a
.byte "		-- Proverbs 18:12",$0a
.byte $0a, 0
fortune250:
.byte "What is the sound of one hand clapping?",$0a
.byte $0a, 0
fortune251:
.byte "BOFH excuse #30:",$0a
.byte "",$0a
.byte "positron router malfunction",$0a
.byte $0a, 0
fortune252:
.byte "The most delightful day after the one on which you buy a cottage in",$0a
.byte "the country is the one on which you resell it.",$0a
.byte "		-- J. Brecheux",$0a
.byte $0a, 0
fortune253:
.byte "If you look good and dress well, you don't need a purpose in life.",$0a
.byte "		-- Robert Pante, fashion consultant",$0a
.byte $0a, 0
fortune254:
.byte "I can't understand it.  I can't even understand the people who can",$0a
.byte "understand it.",$0a
.byte "		-- Queen Juliana of the Netherlands.",$0a
.byte $0a, 0
fortune255:
.byte "Sex is like air.  It's only a big deal if you can't get any.",$0a
.byte $0a, 0
