; MIT License
;
; Copyright (c) 2018 Thomas Woinke, Marko Lauke, www.steckschwein.de
;
; Permission is hereby granted, free of charge, to any person obtaining a copy
; of this software and associated documentation files (the "Software"), to deal
; in the Software without restriction, including without limitation the rights
; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
; copies of the Software, and to permit persons to whom the Software is
; furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in all
; copies or substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
; SOFTWARE.

.include "steckos.inc"
.include "rtc.inc"
appstart $1000
.export char_out=krn_chrout


.importzp ptr1
.import hexout

.code

main:
        lda rtc_systime_t+time_t::tm_sec
        eor rtc_systime_t+time_t::tm_min
        sta seed
        ;jsr hexout

        jsr prnd
        ;jsr hexout

        tay
        lda fortunes_hi,y
        sta ptr1+1
        lda fortunes_lo,y
        sta ptr1

out:

        ldy #0
loop:
        lda (ptr1),y
        beq exit
        jsr krn_chrout
        iny
        bne loop
exit:
		jmp (retvec)

prnd:
        lda seed
        beq doEor
        asl
        beq noEor ;if the input was $80, skip the EOR
        bcc noEor
doEor:  eor #$1d
noEor:  sta seed
        rts

fortunes_hi:
        .byte >fortune0
        .byte >fortune1
        .byte >fortune2
        .byte >fortune3
        .byte >fortune4
        .byte >fortune5
        .byte >fortune6
        .byte >fortune7
        .byte >fortune8
        .byte >fortune9
        .byte >fortune10
        .byte >fortune11
        .byte >fortune12
        .byte >fortune13
        .byte >fortune14
        .byte >fortune15
        .byte >fortune16
        .byte >fortune17
        .byte >fortune18
        .byte >fortune19
        .byte >fortune20
        .byte >fortune21
        .byte >fortune22
        .byte >fortune23
        .byte >fortune24
        .byte >fortune25
        .byte >fortune26
        .byte >fortune27
        .byte >fortune28
        .byte >fortune29
        .byte >fortune30
        .byte >fortune31
        .byte >fortune32
        .byte >fortune33
        .byte >fortune34
        .byte >fortune35
        .byte >fortune36
        .byte >fortune37
        .byte >fortune38
        .byte >fortune39
        .byte >fortune40
        .byte >fortune41
        .byte >fortune42
        .byte >fortune43
        .byte >fortune44
        .byte >fortune45
        .byte >fortune46
        .byte >fortune47
        .byte >fortune48
        .byte >fortune49
        .byte >fortune50
        .byte >fortune51
        .byte >fortune52
        .byte >fortune53
        .byte >fortune54
        .byte >fortune55
        .byte >fortune56
        .byte >fortune57
        .byte >fortune58
        .byte >fortune59
        .byte >fortune60
        .byte >fortune61
        .byte >fortune62
        .byte >fortune63
        .byte >fortune64
        .byte >fortune65
        .byte >fortune66
        .byte >fortune67
        .byte >fortune68
        .byte >fortune69
        .byte >fortune70
        .byte >fortune71
        .byte >fortune72
        .byte >fortune73
        .byte >fortune74
        .byte >fortune75
        .byte >fortune76
        .byte >fortune77
        .byte >fortune78
        .byte >fortune79
        .byte >fortune80
        .byte >fortune81
        .byte >fortune82
        .byte >fortune83
        .byte >fortune84
        .byte >fortune85
        .byte >fortune86
        .byte >fortune87
        .byte >fortune88
        .byte >fortune89
        .byte >fortune90
        .byte >fortune91
        .byte >fortune92
        .byte >fortune93
        .byte >fortune94
        .byte >fortune95
        .byte >fortune96
        .byte >fortune97
        .byte >fortune98
        .byte >fortune99
        .byte >fortune100
        .byte >fortune101
        .byte >fortune102
        .byte >fortune103
        .byte >fortune104
        .byte >fortune105
        .byte >fortune106
        .byte >fortune107
        .byte >fortune108
        .byte >fortune109
        .byte >fortune110
        .byte >fortune111
        .byte >fortune112
        .byte >fortune113
        .byte >fortune114
        .byte >fortune115
        .byte >fortune116
        .byte >fortune117
        .byte >fortune118
        .byte >fortune119
        .byte >fortune120
        .byte >fortune121
        .byte >fortune122
        .byte >fortune123
        .byte >fortune124
        .byte >fortune125
        .byte >fortune126
        .byte >fortune127
        .byte >fortune128
        .byte >fortune129
        .byte >fortune130
        .byte >fortune131
        .byte >fortune132
        .byte >fortune133
        .byte >fortune134
        .byte >fortune135
        .byte >fortune136
        .byte >fortune137
        .byte >fortune138
        .byte >fortune139
        .byte >fortune140
        .byte >fortune141
        .byte >fortune142
        .byte >fortune143
        .byte >fortune144
        .byte >fortune145
        .byte >fortune146
        .byte >fortune147
        .byte >fortune148
        .byte >fortune149
        .byte >fortune150
        .byte >fortune151
        .byte >fortune152
        .byte >fortune153
        .byte >fortune154
        .byte >fortune155
        .byte >fortune156
        .byte >fortune157
        .byte >fortune158
        .byte >fortune159
        .byte >fortune160
        .byte >fortune161
        .byte >fortune162
        .byte >fortune163
        .byte >fortune164
        .byte >fortune165
        .byte >fortune166
        .byte >fortune167
        .byte >fortune168
        .byte >fortune169
        .byte >fortune170
        .byte >fortune171
        .byte >fortune172
        .byte >fortune173
        .byte >fortune174
        .byte >fortune175
        .byte >fortune176
        .byte >fortune177
        .byte >fortune178
        .byte >fortune179
        .byte >fortune180
        .byte >fortune181
        .byte >fortune182
        .byte >fortune183
        .byte >fortune184
        .byte >fortune185
        .byte >fortune186
        .byte >fortune187
        .byte >fortune188
        .byte >fortune189
        .byte >fortune190
        .byte >fortune191
        .byte >fortune192
        .byte >fortune193
        .byte >fortune194
        .byte >fortune195
        .byte >fortune196
        .byte >fortune197
        .byte >fortune198
        .byte >fortune199
        .byte >fortune200
        .byte >fortune201
        .byte >fortune202
        .byte >fortune203
        .byte >fortune204
        .byte >fortune205
        .byte >fortune206
        .byte >fortune207
        .byte >fortune208
        .byte >fortune209
        .byte >fortune210
        .byte >fortune211
        .byte >fortune212
        .byte >fortune213
        .byte >fortune214
        .byte >fortune215
        .byte >fortune216
        .byte >fortune217
        .byte >fortune218
        .byte >fortune219
        .byte >fortune220
        .byte >fortune221
        .byte >fortune222
        .byte >fortune223
        .byte >fortune224
        .byte >fortune225
        .byte >fortune226
        .byte >fortune227
        .byte >fortune228
        .byte >fortune229
        .byte >fortune230
        .byte >fortune231
        .byte >fortune232
        .byte >fortune233
        .byte >fortune234
        .byte >fortune235
        .byte >fortune236
        .byte >fortune237
        .byte >fortune238
        .byte >fortune239
        .byte >fortune240
        .byte >fortune241
        .byte >fortune242
        .byte >fortune243
        .byte >fortune244
        .byte >fortune245
        .byte >fortune246
        .byte >fortune247
        .byte >fortune248
        .byte >fortune249
        .byte >fortune250
        .byte >fortune251
        .byte >fortune252
        .byte >fortune253
        .byte >fortune254
        .byte >fortune255
fortunes_lo:
        .byte <fortune0
        .byte <fortune1
        .byte <fortune2
        .byte <fortune3
        .byte <fortune4
        .byte <fortune5
        .byte <fortune6
        .byte <fortune7
        .byte <fortune8
        .byte <fortune9
        .byte <fortune10
        .byte <fortune11
        .byte <fortune12
        .byte <fortune13
        .byte <fortune14
        .byte <fortune15
        .byte <fortune16
        .byte <fortune17
        .byte <fortune18
        .byte <fortune19
        .byte <fortune20
        .byte <fortune21
        .byte <fortune22
        .byte <fortune23
        .byte <fortune24
        .byte <fortune25
        .byte <fortune26
        .byte <fortune27
        .byte <fortune28
        .byte <fortune29
        .byte <fortune30
        .byte <fortune31
        .byte <fortune32
        .byte <fortune33
        .byte <fortune34
        .byte <fortune35
        .byte <fortune36
        .byte <fortune37
        .byte <fortune38
        .byte <fortune39
        .byte <fortune40
        .byte <fortune41
        .byte <fortune42
        .byte <fortune43
        .byte <fortune44
        .byte <fortune45
        .byte <fortune46
        .byte <fortune47
        .byte <fortune48
        .byte <fortune49
        .byte <fortune50
        .byte <fortune51
        .byte <fortune52
        .byte <fortune53
        .byte <fortune54
        .byte <fortune55
        .byte <fortune56
        .byte <fortune57
        .byte <fortune58
        .byte <fortune59
        .byte <fortune60
        .byte <fortune61
        .byte <fortune62
        .byte <fortune63
        .byte <fortune64
        .byte <fortune65
        .byte <fortune66
        .byte <fortune67
        .byte <fortune68
        .byte <fortune69
        .byte <fortune70
        .byte <fortune71
        .byte <fortune72
        .byte <fortune73
        .byte <fortune74
        .byte <fortune75
        .byte <fortune76
        .byte <fortune77
        .byte <fortune78
        .byte <fortune79
        .byte <fortune80
        .byte <fortune81
        .byte <fortune82
        .byte <fortune83
        .byte <fortune84
        .byte <fortune85
        .byte <fortune86
        .byte <fortune87
        .byte <fortune88
        .byte <fortune89
        .byte <fortune90
        .byte <fortune91
        .byte <fortune92
        .byte <fortune93
        .byte <fortune94
        .byte <fortune95
        .byte <fortune96
        .byte <fortune97
        .byte <fortune98
        .byte <fortune99
        .byte <fortune100
        .byte <fortune101
        .byte <fortune102
        .byte <fortune103
        .byte <fortune104
        .byte <fortune105
        .byte <fortune106
        .byte <fortune107
        .byte <fortune108
        .byte <fortune109
        .byte <fortune110
        .byte <fortune111
        .byte <fortune112
        .byte <fortune113
        .byte <fortune114
        .byte <fortune115
        .byte <fortune116
        .byte <fortune117
        .byte <fortune118
        .byte <fortune119
        .byte <fortune120
        .byte <fortune121
        .byte <fortune122
        .byte <fortune123
        .byte <fortune124
        .byte <fortune125
        .byte <fortune126
        .byte <fortune127
        .byte <fortune128
        .byte <fortune129
        .byte <fortune130
        .byte <fortune131
        .byte <fortune132
        .byte <fortune133
        .byte <fortune134
        .byte <fortune135
        .byte <fortune136
        .byte <fortune137
        .byte <fortune138
        .byte <fortune139
        .byte <fortune140
        .byte <fortune141
        .byte <fortune142
        .byte <fortune143
        .byte <fortune144
        .byte <fortune145
        .byte <fortune146
        .byte <fortune147
        .byte <fortune148
        .byte <fortune149
        .byte <fortune150
        .byte <fortune151
        .byte <fortune152
        .byte <fortune153
        .byte <fortune154
        .byte <fortune155
        .byte <fortune156
        .byte <fortune157
        .byte <fortune158
        .byte <fortune159
        .byte <fortune160
        .byte <fortune161
        .byte <fortune162
        .byte <fortune163
        .byte <fortune164
        .byte <fortune165
        .byte <fortune166
        .byte <fortune167
        .byte <fortune168
        .byte <fortune169
        .byte <fortune170
        .byte <fortune171
        .byte <fortune172
        .byte <fortune173
        .byte <fortune174
        .byte <fortune175
        .byte <fortune176
        .byte <fortune177
        .byte <fortune178
        .byte <fortune179
        .byte <fortune180
        .byte <fortune181
        .byte <fortune182
        .byte <fortune183
        .byte <fortune184
        .byte <fortune185
        .byte <fortune186
        .byte <fortune187
        .byte <fortune188
        .byte <fortune189
        .byte <fortune190
        .byte <fortune191
        .byte <fortune192
        .byte <fortune193
        .byte <fortune194
        .byte <fortune195
        .byte <fortune196
        .byte <fortune197
        .byte <fortune198
        .byte <fortune199
        .byte <fortune200
        .byte <fortune201
        .byte <fortune202
        .byte <fortune203
        .byte <fortune204
        .byte <fortune205
        .byte <fortune206
        .byte <fortune207
        .byte <fortune208
        .byte <fortune209
        .byte <fortune210
        .byte <fortune211
        .byte <fortune212
        .byte <fortune213
        .byte <fortune214
        .byte <fortune215
        .byte <fortune216
        .byte <fortune217
        .byte <fortune218
        .byte <fortune219
        .byte <fortune220
        .byte <fortune221
        .byte <fortune222
        .byte <fortune223
        .byte <fortune224
        .byte <fortune225
        .byte <fortune226
        .byte <fortune227
        .byte <fortune228
        .byte <fortune229
        .byte <fortune230
        .byte <fortune231
        .byte <fortune232
        .byte <fortune233
        .byte <fortune234
        .byte <fortune235
        .byte <fortune236
        .byte <fortune237
        .byte <fortune238
        .byte <fortune239
        .byte <fortune240
        .byte <fortune241
        .byte <fortune242
        .byte <fortune243
        .byte <fortune244
        .byte <fortune245
        .byte <fortune246
        .byte <fortune247
        .byte <fortune248
        .byte <fortune249
        .byte <fortune250
        .byte <fortune251
        .byte <fortune252
        .byte <fortune253
        .byte <fortune254
        .byte <fortune255
seed:    .BYTE 42
.include "fortunes.inc"
