fortune0:
.byte "Prejudice:",$0a
.byte "A vagrant opinion without visible means of support.",$0a
.byte "-- Ambrose Bierce",$0a
.byte $0a, 0
fortune1:
.byte "I can't stand squealers; hit that guy.",$0a
.byte "-- Albert Anastasia",$0a
.byte $0a, 0
fortune2:
.byte "You should avoid hedging, at least that's what I think.",$0a
.byte $0a, 0
fortune3:
.byte "A light wife doth make a heavy husband.",$0a
.byte "-- Wm. Shakespeare, The Merchant of Venice",$0a
.byte $0a, 0
fortune4:
.byte "You will be aided greatly by a person whom you thought to be unimportant.",$0a
.byte $0a, 0
fortune5:
.byte "Colors may fade.",$0a
.byte $0a, 0
fortune6:
.byte "Hey Ivan, check your six.",$0a
.byte "-- Sidewinder missile jacket patch, showing a Sidewinder driving up the tail",$0a
.byte " of a Russian Su-27",$0a
.byte $0a, 0
fortune7:
.byte "A Smith & Wesson beats four aces.",$0a
.byte $0a, 0
fortune8:
.byte "Deliberation, n.:",$0a
.byte "The act of examining one's bread to determine which side it is",$0a
.byte "buttered on.",$0a
.byte "-- Ambrose Bierce, The Devil's Dictionary",$0a
.byte $0a, 0
fortune9:
.byte "What did you bring that book I didn't want to be read to out of about",$0a
.byte "Down Under up for?",$0a
.byte $0a, 0
fortune10:
.byte "What is mind?  No matter.  What is matter?  Never mind.",$0a
.byte "-- Thomas Hewitt Key, 1799-1875",$0a
.byte $0a, 0
fortune11:
.byte "Inheritance taxes are getting so out of line, that the deceased family",$0a
.byte "often doesn't have a legacy to stand on.",$0a
.byte $0a, 0
fortune12:
.byte "Here comes the orator, with his flood of words and his drop of reason.",$0a
.byte $0a, 0
fortune13:
.byte "Minicomputer:",$0a
.byte "A computer that can be afforded on the budget of a middle-level manager.",$0a
.byte $0a, 0
fortune14:
.byte "No other warranty expressed or implied.",$0a
.byte $0a, 0
fortune15:
.byte "It is Fortune, not Wisdom, that rules man's life.",$0a
.byte $0a, 0
fortune16:
.byte "Rebellion lay in his way, and he found it.",$0a
.byte "-- William Shakespeare, Henry IV",$0a
.byte $0a, 0
fortune17:
.byte "#else /* !STDSTDIO */     /* The big, slow, and stupid way */",$0a
.byte "-- Larry Wall in str.c from the perl source code",$0a
.byte $0a, 0
fortune18:
.byte "Nature is very un-American.  Nature never hurries.",$0a
.byte "-- William George Jordan",$0a
.byte $0a, 0
fortune19:
.byte "I disagree with what you say, but will defend to the death your right to",$0a
.byte "tell such LIES!",$0a
.byte $0a, 0
fortune20:
.byte "BOFH excuse #380:",$0a
.byte "",$0a
.byte "Operators killed when huge stack of backup tapes fell over.",$0a
.byte $0a, 0
fortune21:
.byte "Common sense is the collection of prejudices acquired by age eighteen.",$0a
.byte "-- Albert Einstein",$0a
.byte $0a, 0
fortune22:
.byte "Nothing makes a person more productive than the last minute.",$0a
.byte $0a, 0
fortune23:
.byte "You are an insult to my intelligence!  I demand that you log off immediately.",$0a
.byte $0a, 0
fortune24:
.byte "A rock store eventually closed down; they were taking too much for granite.",$0a
.byte $0a, 0
fortune25:
.byte "Is it just me, or does anyone else read `bible humpers' every time",$0a
.byte "someone writes `bible thumpers?'",$0a
.byte "-- Joel M. Snyder, jms@mis.arizona.edu",$0a
.byte $0a, 0
fortune26:
.byte "May you die in bed at 95, shot by a jealous spouse.",$0a
.byte $0a, 0
fortune27:
.byte "Where are the calculations that go with a calculated risk?",$0a
.byte $0a, 0
fortune28:
.byte "<Espy> I invoke Espy's law, which states that you all suck :P",$0a
.byte $0a, 0
fortune29:
.byte "BOFH excuse #310:",$0a
.byte "",$0a
.byte "asynchronous inode failure",$0a
.byte $0a, 0
fortune30:
.byte "Everyone wants results, but no one is willing to do what it takes to get them.",$0a
.byte "-- Dirty Harry",$0a
.byte $0a, 0
fortune31:
.byte "If I can have honesty, it's easier to overlook mistakes.",$0a
.byte "-- Kirk, Space Seed, stardate 3141.9",$0a
.byte $0a, 0
fortune32:
.byte "Are we not men?",$0a
.byte $0a, 0
fortune33:
.byte "Among the lucky, you are the chosen one.",$0a
.byte $0a, 0
fortune34:
.byte "BOFH excuse #426:",$0a
.byte "",$0a
.byte "internet is needed to catch the etherbunny",$0a
.byte $0a, 0
fortune35:
.byte "You are going to have a new love affair.",$0a
.byte $0a, 0
fortune36:
.byte "If built in great numbers, motels will be used for nothing but illegal",$0a
.byte "purposes.",$0a
.byte "-- J. Edgar Hoover",$0a
.byte $0a, 0
fortune37:
.byte "It is a sobering thought that when Mozart was my age, he had been",$0a
.byte "dead for two years.",$0a
.byte "-- Tom Lehrer",$0a
.byte $0a, 0
fortune38:
.byte "Receiving a million dollars tax free will make you feel better than",$0a
.byte "being flat broke and having a stomach ache.",$0a
.byte "-- Dolph Sharp, I'm O.K., You're Not So Hot",$0a
.byte $0a, 0
fortune39:
.byte "What sin has not been committed in the name of efficiency?",$0a
.byte $0a, 0
fortune40:
.byte "There is no comfort without pain; thus we define salvation through suffering.",$0a
.byte "-- Cato",$0a
.byte $0a, 0
fortune41:
.byte "Q:What's the difference between Bell Labs and the Boy Scouts of America?",$0a
.byte "A:The Boy Scouts have adult supervision.",$0a
.byte $0a, 0
fortune42:
.byte "I have gained this by philosophy:",$0a
.byte "that I do without being commanded what others do only from fear of the law.",$0a
.byte "-- Aristotle",$0a
.byte $0a, 0
fortune43:
.byte "It appears that PL/I (and its dialects) is, or will be, the most widely",$0a
.byte "used higher level language for systems programming.",$0a
.byte "-- J. Sammet",$0a
.byte $0a, 0
fortune44:
.byte "BOFH excuse #177:",$0a
.byte "",$0a
.byte "sticktion",$0a
.byte $0a, 0
fortune45:
.byte "The last person who said that (God rest his soul) lived to regret it.",$0a
.byte $0a, 0
fortune46:
.byte "The best definition of a gentleman is a man who can play the accordion --",$0a
.byte "but doesn't.",$0a
.byte "-- Tom Crichton",$0a
.byte $0a, 0
fortune47:
.byte "Danger, you haven't seen the last of me!",$0a
.byte "   No, but the first of you turns my stomach!",$0a
.byte "-- The Firesign Theatre's Nick Danger",$0a
.byte $0a, 0
fortune48:
.byte "BOFH excuse #21:",$0a
.byte "",$0a
.byte "POSIX compliance problem",$0a
.byte $0a, 0
fortune49:
.byte "OS/2 must die!",$0a
.byte $0a, 0
fortune50:
.byte "Inform all the troops that communications have completely broken down.",$0a
.byte $0a, 0
fortune51:
.byte "Test-tube babies shouldn't throw stones.",$0a
.byte $0a, 0
fortune52:
.byte "Remember kids, if there's a loaded gun in the room, be sure that you're the",$0a
.byte "one holding it",$0a
.byte "-- Captain Combat",$0a
.byte $0a, 0
fortune53:
.byte "You need tender loving care once a week - so that I can slap you into shape.",$0a
.byte "-- Ellyn Mustard",$0a
.byte $0a, 0
fortune54:
.byte "What good is an obscenity trial except to popularize literature?",$0a
.byte "-- Nero Wolfe, The League of Frightened Men",$0a
.byte $0a, 0
fortune55:
.byte "Entropy isn't what it used to be.",$0a
.byte $0a, 0
fortune56:
.byte "It's not whether you win or lose, it's how you look playing the game.",$0a
.byte $0a, 0
fortune57:
.byte "Dreams are free, but you get soaked on the connect time.",$0a
.byte $0a, 0
fortune58:
.byte "You knew the job was dangerous when you took it, Fred.",$0a
.byte "-- Superchicken",$0a
.byte $0a, 0
fortune59:
.byte "How long a minute is depends on which side of the bathroom door you're on.",$0a
.byte $0a, 0
fortune60:
.byte "You always have the option of pitching baseballs at empty spray paint cans",$0a
.byte "in a cul-de-sac in a Cleveland suburb.",$0a
.byte $0a, 0
fortune61:
.byte "We are anthill men upon an anthill world.",$0a
.byte "-- Ray Bradbury",$0a
.byte $0a, 0
fortune62:
.byte "Remember, even if you win the rat race -- you're still a rat.",$0a
.byte $0a, 0
fortune63:
.byte "A farmer is a man outstanding in his field.",$0a
.byte $0a, 0
fortune64:
.byte "A commune is where people join together to share their lack of wealth.",$0a
.byte "-- R. Stallman",$0a
.byte $0a, 0
fortune65:
.byte "This ASEXUAL PIG really BOILS my BLOOD ... He's so ... so ... URGENT!!",$0a
.byte $0a, 0
fortune66:
.byte "Every improvement in communication makes the bore more terrible.",$0a
.byte "-- Frank Moore Colby",$0a
.byte $0a, 0
fortune67:
.byte "Linux, the way to get rid of boot viruses",$0a
.byte "-- MaDsen Wikholm, mwikholm@at8.abo.fi",$0a
.byte $0a, 0
fortune68:
.byte "BOFH excuse #353:",$0a
.byte "",$0a
.byte "Second-system effect.",$0a
.byte $0a, 0
fortune69:
.byte "Why should we subsidize intellectual curiosity?",$0a
.byte "-- Ronald Reagan",$0a
.byte $0a, 0
fortune70:
.byte "Political T.V. commercials prove one thing: some candidates can tell",$0a
.byte "all their good points and qualifications in just 30 seconds.",$0a
.byte $0a, 0
fortune71:
.byte "Love and scandal are the best sweeteners of tea.",$0a
.byte $0a, 0
fortune72:
.byte "Do not seek death; death will find you.  But seek the road which makes death",$0a
.byte "a fulfillment.",$0a
.byte "-- Dag Hammarskjold",$0a
.byte $0a, 0
fortune73:
.byte "All your files have been destroyed (sorry).  Paul.",$0a
.byte $0a, 0
fortune74:
.byte "BOFH excuse #210:",$0a
.byte "",$0a
.byte "We didn't pay the Internet bill and it's been cut off.",$0a
.byte $0a, 0
fortune75:
.byte "Newlan's Truism:",$0a
.byte "An acceptable level of unemployment means that the",$0a
.byte "government economist to whom it is acceptable still has a job.",$0a
.byte $0a, 0
fortune76:
.byte "A visit to a strange place will bring fresh work.",$0a
.byte $0a, 0
fortune77:
.byte "Contains no artificial colors or ingredients.",$0a
.byte $0a, 0
fortune78:
.byte "Paranoids are people, too; they have their own problems.  It's easy",$0a
.byte "to criticize, but if everybody hated you, you'd be paranoid too.",$0a
.byte "-- D. J. Hicks",$0a
.byte $0a, 0
fortune79:
.byte "Nullum magnum ingenium sine mixtura dementiae fuit.",$0a
.byte "[There is no great genius without some touch of madness.]",$0a
.byte "-- Seneca",$0a
.byte $0a, 0
fortune80:
.byte "Eat right, stay fit, and die anyway.",$0a
.byte $0a, 0
fortune81:
.byte "A gambler's biggest thrill is winning a bet.",$0a
.byte "His next biggest thrill is losing a bet.",$0a
.byte $0a, 0
fortune82:
.byte "The absurd is the essential concept and the first truth.",$0a
.byte "-- A. Camus",$0a
.byte $0a, 0
fortune83:
.byte "My idea of roughing it turning the air conditioner too low.",$0a
.byte $0a, 0
fortune84:
.byte "Anybody can win, unless there happens to be a second entry.",$0a
.byte $0a, 0
fortune85:
.byte "If you're careful enough, nothing bad or good will ever happen to you.",$0a
.byte $0a, 0
fortune86:
.byte "The best laid plans of mice and men are held up in the legal department.",$0a
.byte $0a, 0
fortune87:
.byte "Everybody is somebody else's weirdo.",$0a
.byte "-- Dykstra",$0a
.byte $0a, 0
fortune88:
.byte "To our sweethearts and wives.  May they never meet.",$0a
.byte "-- 19th century toast",$0a
.byte $0a, 0
fortune89:
.byte "Overload -- core meltdown sequence initiated.",$0a
.byte $0a, 0
fortune90:
.byte "La-dee-dee, la-dee-dah.",$0a
.byte $0a, 0
fortune91:
.byte "I know you think you thought you knew what you thought I said,",$0a
.byte "but I'm not sure you understood what you thought I meant.",$0a
.byte $0a, 0
fortune92:
.byte "Hat check girl:",$0a
.byte "Goodness!  What lovely diamonds!",$0a
.byte "Mae West:",$0a
.byte "Goodness had nothin' to do with it, dearie.",$0a
.byte "-- Night After Night, 1932",$0a
.byte $0a, 0
fortune93:
.byte "To love is good, love being difficult.",$0a
.byte $0a, 0
fortune94:
.byte "It's kind of fun to do the impossible.",$0a
.byte "-- Walt Disney",$0a
.byte $0a, 0
fortune95:
.byte "He that is giddy thinks the world turns round.",$0a
.byte "-- William Shakespeare, The Taming of the Shrew",$0a
.byte $0a, 0
fortune96:
.byte "Nice guys don't finish nice.",$0a
.byte $0a, 0
fortune97:
.byte "BOFH excuse #435:",$0a
.byte "",$0a
.byte "Internet shut down due to maintenance",$0a
.byte $0a, 0
fortune98:
.byte "<james> but, then I used an Atari, I was more likely to win the lottery in",$0a
.byte "        ten countries simultaneously than get accelerated X",$0a
.byte $0a, 0
fortune99:
.byte "The FALAFEL SANDWICH lands on my HEAD and I become a VEGETARIAN ...",$0a
.byte $0a, 0
fortune100:
.byte "Eschew obfuscation.",$0a
.byte $0a, 0
fortune101:
.byte "grep me no patterns and I'll tell you no lines.",$0a
.byte $0a, 0
fortune102:
.byte "Today is the last day of your life so far.",$0a
.byte $0a, 0
fortune103:
.byte "I'd love to kiss you, but I just washed my hair.",$0a
.byte "-- Bette Davis, Cabin in the Cotton",$0a
.byte $0a, 0
fortune104:
.byte "He who wonders discovers that this in itself is wonder.",$0a
.byte "-- M. C. Escher",$0a
.byte $0a, 0
fortune105:
.byte "Yow!  Am I in Milwaukee?",$0a
.byte $0a, 0
fortune106:
.byte "Ah, but a man's grasp should exceed his reach,",$0a
.byte "Or what's a heaven for ?",$0a
.byte "-- Robert Browning, Andrea del Sarto",$0a
.byte $0a, 0
fortune107:
.byte "A lot of people I know believe in positive thinking, and so do I.  I",$0a
.byte "believe everything positively stinks.",$0a
.byte "-- Lew Col",$0a
.byte $0a, 0
fortune108:
.byte "The difference between a lawyer and a rooster is that",$0a
.byte "the rooster gets up in the morning and clucks defiance.",$0a
.byte $0a, 0
fortune109:
.byte "You know it's going to be a long day when you get up, shave and shower,",$0a
.byte "start to get dressed and your shoes are still warm.",$0a
.byte "-- Dean Webber",$0a
.byte $0a, 0
fortune110:
.byte "Must be over 21.",$0a
.byte $0a, 0
fortune111:
.byte "Be independent.  Insult a rich relative today.",$0a
.byte $0a, 0
fortune112:
.byte "Robustness, adj.:",$0a
.byte "Never having to say you're sorry.",$0a
.byte $0a, 0
fortune113:
.byte "If you don't do the things that are not worth doing, who will?",$0a
.byte $0a, 0
fortune114:
.byte "When you speak to others for their own good it's advice;",$0a
.byte "when they speak to you for your own good it's interference.",$0a
.byte $0a, 0
fortune115:
.byte "Many hands make light work.",$0a
.byte "-- John Heywood",$0a
.byte $0a, 0
fortune116:
.byte "Speak softly and carry a +6 two-handed sword.",$0a
.byte $0a, 0
fortune117:
.byte "Save yourself from the 'Gates' of hell, use Linux.  -- like that one.",$0a
.byte "-- The_Kind @ LinuxNet",$0a
.byte $0a, 0
fortune118:
.byte "BOFH excuse #109:",$0a
.byte "",$0a
.byte "The electricity substation in the car park blew up.",$0a
.byte $0a, 0
fortune119:
.byte "In my end is my beginning.",$0a
.byte "-- Mary Stuart, Queen of Scots",$0a
.byte $0a, 0
fortune120:
.byte "Your object is to save the world, while still leading a pleasant life.",$0a
.byte $0a, 0
fortune121:
.byte "Give me a Plumber's friend the size of the Pittsburgh dome, and a place",$0a
.byte "to stand, and I will drain the world.",$0a
.byte $0a, 0
fortune122:
.byte "Four thousand different MAGNATES, MOGULS & NABOBS are romping in my",$0a
.byte "gothic solarium!!",$0a
.byte $0a, 0
fortune123:
.byte "I try to keep an open mind, but not so open that my brains fall out.",$0a
.byte "-- Judge Harold T. Stone",$0a
.byte $0a, 0
fortune124:
.byte "You can bear anything if it isn't your own fault.",$0a
.byte "-- Katharine Fullerton Gerould",$0a
.byte $0a, 0
fortune125:
.byte "And on the seventh day, He exited from append mode.",$0a
.byte $0a, 0
fortune126:
.byte "An infallible method of conciliating a tiger is to allow oneself to be",$0a
.byte "devoured.",$0a
.byte "-- Konrad Adenauer",$0a
.byte $0a, 0
fortune127:
.byte "One planet is all you get.",$0a
.byte $0a, 0
fortune128:
.byte "Statistics are no substitute for judgement.",$0a
.byte "-- Henry Clay",$0a
.byte $0a, 0
fortune129:
.byte "If you keep your mind sufficiently open, people will throw a lot of",$0a
.byte "rubbish into it.",$0a
.byte "-- William Orton",$0a
.byte $0a, 0
fortune130:
.byte "In America, it's not how much an item costs, it's how much you save.",$0a
.byte $0a, 0
fortune131:
.byte "Humor in the Court:",$0a
.byte "Q: (Showing man picture.) That's you?",$0a
.byte "A: Yes, sir.",$0a
.byte "Q: And you were present when the picture was taken, right?",$0a
.byte $0a, 0
fortune132:
.byte "There's nothing like a girl with a plunging neckline to keep a man on his toes.",$0a
.byte $0a, 0
fortune133:
.byte "Some marriages are made in heaven -- but so are thunder and lightning.",$0a
.byte $0a, 0
fortune134:
.byte "Never go to a doctor whose office plants have died.",$0a
.byte "-- Erma Bombeck",$0a
.byte $0a, 0
fortune135:
.byte "The grass is always greener on the other side of your sunglasses.",$0a
.byte $0a, 0
fortune136:
.byte "Mistakes are often the stepping stones to utter failure.",$0a
.byte $0a, 0
fortune137:
.byte "Killing is stupid; useless!",$0a
.byte "-- McCoy, A Private Little War, stardate 4211.8",$0a
.byte $0a, 0
fortune138:
.byte "A Difficulty for Every Solution.",$0a
.byte "-- Motto of the Federal Civil Service",$0a
.byte $0a, 0
fortune139:
.byte "When women kiss it always reminds one of prize fighters shaking hands.",$0a
.byte "-- H. L. Mencken, Sententiae",$0a
.byte $0a, 0
fortune140:
.byte "When childhood dies, its corpses are called adults.",$0a
.byte "-- Brian Aldiss",$0a
.byte $0a, 0
fortune141:
.byte "Two can Live as Cheaply as One for Half as Long.",$0a
.byte "-- Howard Kandel",$0a
.byte $0a, 0
fortune142:
.byte "Some men are discovered; others are found out.",$0a
.byte $0a, 0
fortune143:
.byte "And so it was, later,",$0a
.byte "As the miller told his tale,",$0a
.byte "That her face, at first just ghostly,",$0a
.byte "Turned a whiter shade of pale.",$0a
.byte "-- Procol Harum",$0a
.byte $0a, 0
fortune144:
.byte "Harrison's Postulate:",$0a
.byte "For every action, there is an equal and opposite criticism.",$0a
.byte $0a, 0
fortune145:
.byte "It's been a business doing pleasure with you.",$0a
.byte $0a, 0
fortune146:
.byte "  We must believe in free will. We have no choice. -Isaac B. Singer",$0a
.byte $0a, 0
fortune147:
.byte "(1) Never draw what you can copy.",$0a
.byte "(2) Never copy what you can trace.",$0a
.byte "(3) Never trace what you can cut out and paste down.",$0a
.byte $0a, 0
fortune148:
.byte "Not that I have anything much against redundancy.  But I said that already.",$0a
.byte "-- Larry Wall in <199702271735.JAA04048@wall.org>",$0a
.byte $0a, 0
fortune149:
.byte "Where's the Coke machine?  Tell me a joke!!",$0a
.byte $0a, 0
fortune150:
.byte "If at first you don't succeed, you're doing about average.",$0a
.byte "-- Leonard Levinson",$0a
.byte $0a, 0
fortune151:
.byte "I'm having a BIG BANG THEORY!!",$0a
.byte $0a, 0
fortune152:
.byte "No matter how subtle the wizard, a knife in the shoulder blades will seriously",$0a
.byte "cramp his style.",$0a
.byte $0a, 0
fortune153:
.byte "Remember: While root can do most everything, there are certain",$0a
.byte "privileges that only a partner can grant.",$0a
.byte "-- Telsa Gwynne",$0a
.byte $0a, 0
fortune154:
.byte "Yow!  I just went below the poverty line!",$0a
.byte $0a, 0
fortune155:
.byte "However, never daunted, I will cope with adversity in my traditional",$0a
.byte "manner ... sulking and nausea.",$0a
.byte "-- Tom K. Ryan",$0a
.byte $0a, 0
fortune156:
.byte "Man 1:Ask me the what the most important thing about telling a good joke is.",$0a
.byte "",$0a
.byte "Man 2:OK, what is the most impo --",$0a
.byte "",$0a
.byte "Man 1:______TIMING!",$0a
.byte $0a, 0
fortune157:
.byte "If you flaunt it, expect to have it trashed.",$0a
.byte $0a, 0
fortune158:
.byte "When a person goes on a diet, the first thing he loses is his temper.",$0a
.byte $0a, 0
fortune159:
.byte "With/Without - and who'll deny it's what the fighting's all about?",$0a
.byte "-- Pink Floyd",$0a
.byte $0a, 0
fortune160:
.byte "It's all magic.  :-)",$0a
.byte "-- Larry Wall in <7282@jpl-devvax.JPL.NASA.GOV>",$0a
.byte $0a, 0
fortune161:
.byte "BOFH excuse #185:",$0a
.byte "",$0a
.byte "system consumed all the paper for paging",$0a
.byte $0a, 0
fortune162:
.byte "So many men; so little time.",$0a
.byte $0a, 0
fortune163:
.byte "I wish I was on a Cincinnati street corner holding a clean dog!",$0a
.byte $0a, 0
fortune164:
.byte "Just because he's dead is no reason to lay off work.",$0a
.byte $0a, 0
fortune165:
.byte "Don't stop to stomp ants when the elephants are stampeding.",$0a
.byte $0a, 0
fortune166:
.byte "To err is human, but when the eraser wears out before the pencil,",$0a
.byte "you're overdoing it a little.",$0a
.byte $0a, 0
fortune167:
.byte "Shick's Law:",$0a
.byte "There is no problem a good miracle can't solve.",$0a
.byte $0a, 0
fortune168:
.byte "The human brain is like an enormous fish -- it is flat and slimy and",$0a
.byte "has gills through which it can see.",$0a
.byte "-- Monty Python",$0a
.byte $0a, 0
fortune169:
.byte "Uh-oh!!  I forgot to submit to COMPULSORY URINALYSIS!",$0a
.byte $0a, 0
fortune170:
.byte "The hottest places in Hell are reserved for those who, in times of moral",$0a
.byte "crisis, preserved their neutrality.",$0a
.byte "-- Dante",$0a
.byte $0a, 0
fortune171:
.byte "Hardware, n.:",$0a
.byte "The parts of a computer system that can be kicked.",$0a
.byte $0a, 0
fortune172:
.byte "Magpie, n.:",$0a
.byte "A bird whose theivish disposition suggested to someone that it",$0a
.byte "might be taught to talk.",$0a
.byte "-- Ambrose Bierce, The Devil's Dictionary",$0a
.byte $0a, 0
fortune173:
.byte "It is all right to hold a conversation, but you should let go of it",$0a
.byte "now and then.",$0a
.byte "-- Richard Armour",$0a
.byte $0a, 0
fortune174:
.byte "Of all the tyrannies that affect mankind, tyranny in religion is the worst.",$0a
.byte "-- Thomas Paine",$0a
.byte $0a, 0
fortune175:
.byte "The price of greatness is responsibility.",$0a
.byte $0a, 0
fortune176:
.byte "QOTD:",$0a
.byte "I'll listen to reason when it comes out on CD.",$0a
.byte $0a, 0
fortune177:
.byte "A witty saying proves nothing, but saying something pointless gets",$0a
.byte "people's attention.",$0a
.byte $0a, 0
fortune178:
.byte "We learn from history that we learn nothing from history.",$0a
.byte "-- George Bernard Shaw",$0a
.byte $0a, 0
fortune179:
.byte "The end of labor is to gain leisure.",$0a
.byte $0a, 0
fortune180:
.byte "Good leaders being scarce, following yourself is allowed.",$0a
.byte $0a, 0
fortune181:
.byte "Real programmers don't bring brown-bag lunches.  If the vending machine",$0a
.byte "doesn't sell it, they don't eat it.  Vending machines don't sell quiche.",$0a
.byte $0a, 0
fortune182:
.byte "How much does she love you?  Less than you'll ever know.",$0a
.byte $0a, 0
fortune183:
.byte "OK, now let's look at four dimensions on the blackboard.",$0a
.byte "-- Dr. Joy",$0a
.byte $0a, 0
fortune184:
.byte "Plastic...  Aluminum...  These are the inheritors of the Universe!",$0a
.byte "Flesh and Blood have had their day... and that day is past!",$0a
.byte "-- Green Lantern Comics",$0a
.byte $0a, 0
fortune185:
.byte "I demand IMPUNITY!",$0a
.byte $0a, 0
fortune186:
.byte "Never let your schooling interfere with your education.",$0a
.byte $0a, 0
fortune187:
.byte "I never killed a man that didn't deserve it.",$0a
.byte "-- Mickey Cohen",$0a
.byte $0a, 0
fortune188:
.byte "As well look for a needle in a bottle of hay.",$0a
.byte "-- Miguel de Cervantes",$0a
.byte $0a, 0
fortune189:
.byte "<Overfiend> this is the New Overfiend, preacher of Love and Tolerance",$0a
.byte $0a, 0
fortune190:
.byte "If you want me to be a good little bunny just dangle some carats in front",$0a
.byte "of my nose.",$0a
.byte "-- Lauren Bacall",$0a
.byte $0a, 0
fortune191:
.byte "No man is an island if he's on at least one mailing list.",$0a
.byte $0a, 0
fortune192:
.byte "* * * * * THIS TERMINAL IS IN USE * * * * *",$0a
.byte $0a, 0
fortune193:
.byte "<Tarzan> hey did you fall off your pirch or something?",$0a
.byte "<knghtbrd> me?  heh.",$0a
.byte $0a, 0
fortune194:
.byte "I will always love the false image I had of you.",$0a
.byte $0a, 0
fortune195:
.byte "The human race is a race of cowards; and I am not only marching in that",$0a
.byte "procession but carrying a banner.",$0a
.byte "-- Mark Twain",$0a
.byte $0a, 0
fortune196:
.byte "We'll pivot at warp 2 and bring all tubes to bear, Mr. Sulu!",$0a
.byte $0a, 0
fortune197:
.byte "There are new messages.",$0a
.byte $0a, 0
fortune198:
.byte "Alimony is the curse of the writing classes.",$0a
.byte "-- Norman Mailer",$0a
.byte $0a, 0
fortune199:
.byte "Who is General Failure and why is he reading my hard disk ?",$0a
.byte "Microsoft spel chekar vor sail, worgs grate !!",$0a
.byte "(By leitner@inf.fu-berlin.de, Felix von Leitner)",$0a
.byte $0a, 0
fortune200:
.byte "You've got to think about tomorrow!",$0a
.byte "TOMORROW!  I haven't even prepared for *_________yesterday* yet!",$0a
.byte $0a, 0
fortune201:
.byte "And do you think (fop that I am) that I could be the Scarlet Pumpernickel?",$0a
.byte "-- Looney Tunes, The Scarlet Pumpernickel (1950, Chuck Jones)",$0a
.byte $0a, 0
fortune202:
.byte "When I sell liquor, it's called bootlegging; when my patrons serve",$0a
.byte "it on silver trays on Lake Shore Drive, it's called hospitality.",$0a
.byte "-- Al Capone",$0a
.byte $0a, 0
fortune203:
.byte "Moe:Wanna play poker tonight?",$0a
.byte "Joe:I can't. It's the kids' night out.",$0a
.byte "Moe:So?",$0a
.byte "Joe:I gotta stay home with the nurse.",$0a
.byte $0a, 0
fortune204:
.byte "It has just been discovered that research causes cancer in rats.",$0a
.byte $0a, 0
fortune205:
.byte "Consistency requires you to be as ignorant today as you were a year ago.",$0a
.byte "-- Bernard Berenson",$0a
.byte $0a, 0
fortune206:
.byte "Meekness is uncommon patience in planning a worthwhile revenge.",$0a
.byte $0a, 0
fortune207:
.byte "Health nuts are going to feel stupid someday, lying in hospitals dying",$0a
.byte "of nothing.",$0a
.byte "-- Redd Foxx",$0a
.byte $0a, 0
fortune208:
.byte "The attacker must vanquish; the defender need only survive.",$0a
.byte $0a, 0
fortune209:
.byte "If you fail to plan, plan to fail.",$0a
.byte $0a, 0
fortune210:
.byte "The last time I saw him he was walking down Lover's Lane holding his own hand.",$0a
.byte "-- Fred Allen",$0a
.byte $0a, 0
fortune211:
.byte "Always remember that you are unique.  Just like everyone else.",$0a
.byte $0a, 0
fortune212:
.byte "Parkinson's Law:  Work expands to fill the time alloted it.",$0a
.byte $0a, 0
fortune213:
.byte "What, after all, is a halo?  It's only one more thing to keep clean.",$0a
.byte "-- Christopher Fry",$0a
.byte $0a, 0
fortune214:
.byte "No, that'd be silly.",$0a
.byte "-- Larry Wall in <199710221710.KAA24242@wall.org>",$0a
.byte $0a, 0
fortune215:
.byte "Coward, n.:",$0a
.byte "One who in a perilous emergency thinks with his legs.",$0a
.byte "-- Ambrose Bierce, The Devil's Dictionary",$0a
.byte $0a, 0
fortune216:
.byte "How much net work could a network work, if a network could net work?",$0a
.byte $0a, 0
fortune217:
.byte "If we can ever make red tape nutritional, we can feed the world.",$0a
.byte "-- R. Schaeberle, Management Accounting",$0a
.byte $0a, 0
fortune218:
.byte "It's better to burn out than to fade away.",$0a
.byte $0a, 0
fortune219:
.byte "Any program which runs right is obsolete.",$0a
.byte $0a, 0
fortune220:
.byte "Steele's Law:",$0a
.byte "There exist tasks which cannot be done by more than ten men",$0a
.byte "or fewer than one hundred.",$0a
.byte $0a, 0
fortune221:
.byte "Hearts will never be practical until they can be made unbreakable.",$0a
.byte "-- The Wizard of Oz",$0a
.byte $0a, 0
fortune222:
.byte "Drop in any mailbox.",$0a
.byte $0a, 0
fortune223:
.byte "An elephant is a mouse with an operating system.",$0a
.byte $0a, 0
fortune224:
.byte "After your lover has gone you will still have PEANUT BUTTER!",$0a
.byte $0a, 0
fortune225:
.byte "Loni Anderson's hair should be LEGALIZED!!",$0a
.byte $0a, 0
fortune226:
.byte "No other warranty expressed or implied.",$0a
.byte $0a, 0
fortune227:
.byte "Oh what wouldn't I give to be spat at in the face...",$0a
.byte "-- a prisoner in Life of Brian",$0a
.byte $0a, 0
fortune228:
.byte "If parents would only realize how they bore their children.",$0a
.byte "-- G. B. Shaw",$0a
.byte $0a, 0
fortune229:
.byte "BOFH excuse #447:",$0a
.byte "",$0a
.byte "According to Microsoft, it's by design",$0a
.byte $0a, 0
fortune230:
.byte "A No uttered from deepest conviction is better and greater than a",$0a
.byte "Yes merely uttered to please, or what is worse, to avoid trouble.",$0a
.byte "-- Mahatma Gandhi",$0a
.byte $0a, 0
fortune231:
.byte "You will reach the highest possible point in your business or profession.",$0a
.byte $0a, 0
fortune232:
.byte "The devil finds work for idle circuits to do.",$0a
.byte $0a, 0
fortune233:
.byte "The only real argument for marriage is that it remains the best method",$0a
.byte "for getting acquainted.",$0a
.byte "-- Heywood Broun",$0a
.byte $0a, 0
fortune234:
.byte "Stay away from flying saucers today.",$0a
.byte $0a, 0
fortune235:
.byte "There are no great men, buster.  There are only men.",$0a
.byte "-- Elaine Stewart, The Bad and the Beautiful",$0a
.byte $0a, 0
fortune236:
.byte "You will be surrounded by luxury.",$0a
.byte $0a, 0
fortune237:
.byte "Who loves not wisely but too well",$0a
.byte "Will look on Helen's face in hell,",$0a
.byte "But he whose love is thin and wise",$0a
.byte "Will view John Knox in Paradise.",$0a
.byte "-- Dorothy Parker",$0a
.byte $0a, 0
fortune238:
.byte "When a man is tired of London, he is tired of life.",$0a
.byte "-- Samuel Johnson",$0a
.byte $0a, 0
fortune239:
.byte "Everyone is in the best seat.",$0a
.byte "-- John Cage",$0a
.byte $0a, 0
fortune240:
.byte "Running Windows on a Pentium is like having a brand new Porsche but only",$0a
.byte "be able to drive backwards with the handbrake on.",$0a
.byte "(Unknown source)",$0a
.byte $0a, 0
fortune241:
.byte "Men take only their needs into consideration -- never their abilities.",$0a
.byte "-- Napoleon Bonaparte",$0a
.byte $0a, 0
fortune242:
.byte "Do what comes naturally.  Seethe and fume and throw a tantrum.",$0a
.byte $0a, 0
fortune243:
.byte "All is fear in love and war.",$0a
.byte $0a, 0
fortune244:
.byte "A beer delayed is a beer denied.",$0a
.byte $0a, 0
fortune245:
.byte "If you write something wrong enough, I'll be glad to make up a new",$0a
.byte "witticism just for you.",$0a
.byte "-- Larry Wall in <199702221943.LAA20388@wall.org>",$0a
.byte $0a, 0
fortune246:
.byte "It may or may not be worthwhile, but it still has to be done.",$0a
.byte $0a, 0
fortune247:
.byte "Genius is ten percent inspiration and fifty percent capital gains.",$0a
.byte $0a, 0
fortune248:
.byte "Distrust all those who love you extremely upon a very slight acquaintance",$0a
.byte "and without any visible reason.",$0a
.byte "-- Lord Chesterfield",$0a
.byte $0a, 0
fortune249:
.byte "I've read SEVEN MILLION books!!",$0a
.byte $0a, 0
fortune250:
.byte "I knew one thing: as soon as anyone said you didn't need a gun, you'd better",$0a
.byte "take one along that worked.",$0a
.byte "-- Raymond Chandler",$0a
.byte $0a, 0
fortune251:
.byte "Confessions may be good for the soul, but they are bad for the reputation.",$0a
.byte "-- Lord Thomas Dewar",$0a
.byte $0a, 0
fortune252:
.byte "Ummm, well, OK.  The network's the network, the computer's the computer.",$0a
.byte "Sorry for the confusion.",$0a
.byte "-- Sun Microsystems",$0a
.byte $0a, 0
fortune253:
.byte "Science and religion are in full accord but science and faith are in complete",$0a
.byte "discord.",$0a
.byte $0a, 0
fortune254:
.byte "I don't know what Descartes' got,",$0a
.byte "But booze can do what Kant cannot.",$0a
.byte "-- Mike Cross",$0a
.byte $0a, 0
fortune255:
.byte "The most important service rendered by the press is that of educating",$0a
.byte "people to approach printed matter with distrust.",$0a
.byte $0a, 0
