name: Build and Test SteckOS and Tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/steckschwein/buildenv:main

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      run: export CC65_HOME=/cc65/ && make
    - name: test
      run: export CC65_HOME=/cc65/ && make test
