name: Build and Test SteckOS and Tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: steckschwein/buildenv:v2_19-alpine

    steps:
    - uses: actions/checkout@v3
    - name: Build 
      run: echo Hello World
