name: Build and Test SteckOS and Tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: steckschwein/buildenv:v2_19-alpine

    steps:
    - uses: actions/checkout@v2
    - name: Prepare build environment
      run: cc65