name: Build docker image for build env

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build docker image
      run: docker build . --file buildenv/Dockerfile.alpine --tag steckschwein/buildenv:2_19-alpine-nouser
