name: Build and Test SteckOS and Tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: 
      image: steckschwein/buildenv:v2_19-alpine
      options: --user root

    steps:
    - name: checkout
      uses: actions/checkout@v3