name: Build and Test SteckOS and Tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare build environment
      run: apt-get install --no-install-recommends -y gcc make libc-dev git python3 python3-pip