name: Build and Test SteckOS and Tools

on:
  push:
    branches: [ "master", "feature/ssw2.0" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: 
      image: steckschwein/buildenv:2_19-alpine-nouser

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build 
      run: export CC65_HOME=/cc65/ && make
    - name: test
      run: export CC65_HOME=/cc65/ && make test
